//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomerMappingInitParameters) DeepCopyInto(out *CustomerMappingInitParameters) {
	*out = *in
	if in.EventPayloadKey != nil {
		in, out := &in.EventPayloadKey, &out.EventPayloadKey
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomerMappingInitParameters.
func (in *CustomerMappingInitParameters) DeepCopy() *CustomerMappingInitParameters {
	if in == nil {
		return nil
	}
	out := new(CustomerMappingInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomerMappingObservation) DeepCopyInto(out *CustomerMappingObservation) {
	*out = *in
	if in.EventPayloadKey != nil {
		in, out := &in.EventPayloadKey, &out.EventPayloadKey
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomerMappingObservation.
func (in *CustomerMappingObservation) DeepCopy() *CustomerMappingObservation {
	if in == nil {
		return nil
	}
	out := new(CustomerMappingObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomerMappingParameters) DeepCopyInto(out *CustomerMappingParameters) {
	*out = *in
	if in.EventPayloadKey != nil {
		in, out := &in.EventPayloadKey, &out.EventPayloadKey
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomerMappingParameters.
func (in *CustomerMappingParameters) DeepCopy() *CustomerMappingParameters {
	if in == nil {
		return nil
	}
	out := new(CustomerMappingParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultAggregationInitParameters) DeepCopyInto(out *DefaultAggregationInitParameters) {
	*out = *in
	if in.Formula != nil {
		in, out := &in.Formula, &out.Formula
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultAggregationInitParameters.
func (in *DefaultAggregationInitParameters) DeepCopy() *DefaultAggregationInitParameters {
	if in == nil {
		return nil
	}
	out := new(DefaultAggregationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultAggregationObservation) DeepCopyInto(out *DefaultAggregationObservation) {
	*out = *in
	if in.Formula != nil {
		in, out := &in.Formula, &out.Formula
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultAggregationObservation.
func (in *DefaultAggregationObservation) DeepCopy() *DefaultAggregationObservation {
	if in == nil {
		return nil
	}
	out := new(DefaultAggregationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultAggregationParameters) DeepCopyInto(out *DefaultAggregationParameters) {
	*out = *in
	if in.Formula != nil {
		in, out := &in.Formula, &out.Formula
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultAggregationParameters.
func (in *DefaultAggregationParameters) DeepCopy() *DefaultAggregationParameters {
	if in == nil {
		return nil
	}
	out := new(DefaultAggregationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Meter) DeepCopyInto(out *Meter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Meter.
func (in *Meter) DeepCopy() *Meter {
	if in == nil {
		return nil
	}
	out := new(Meter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Meter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeterInitParameters) DeepCopyInto(out *MeterInitParameters) {
	*out = *in
	if in.CustomerMapping != nil {
		in, out := &in.CustomerMapping, &out.CustomerMapping
		*out = make([]CustomerMappingInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DefaultAggregation != nil {
		in, out := &in.DefaultAggregation, &out.DefaultAggregation
		*out = make([]DefaultAggregationInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.EventName != nil {
		in, out := &in.EventName, &out.EventName
		*out = new(string)
		**out = **in
	}
	if in.EventTimeWindow != nil {
		in, out := &in.EventTimeWindow, &out.EventTimeWindow
		*out = new(string)
		**out = **in
	}
	if in.ValueSettings != nil {
		in, out := &in.ValueSettings, &out.ValueSettings
		*out = make([]ValueSettingsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeterInitParameters.
func (in *MeterInitParameters) DeepCopy() *MeterInitParameters {
	if in == nil {
		return nil
	}
	out := new(MeterInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeterList) DeepCopyInto(out *MeterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Meter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeterList.
func (in *MeterList) DeepCopy() *MeterList {
	if in == nil {
		return nil
	}
	out := new(MeterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MeterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeterObservation) DeepCopyInto(out *MeterObservation) {
	*out = *in
	if in.CustomerMapping != nil {
		in, out := &in.CustomerMapping, &out.CustomerMapping
		*out = make([]CustomerMappingObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DefaultAggregation != nil {
		in, out := &in.DefaultAggregation, &out.DefaultAggregation
		*out = make([]DefaultAggregationObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.EventName != nil {
		in, out := &in.EventName, &out.EventName
		*out = new(string)
		**out = **in
	}
	if in.EventTimeWindow != nil {
		in, out := &in.EventTimeWindow, &out.EventTimeWindow
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ValueSettings != nil {
		in, out := &in.ValueSettings, &out.ValueSettings
		*out = make([]ValueSettingsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeterObservation.
func (in *MeterObservation) DeepCopy() *MeterObservation {
	if in == nil {
		return nil
	}
	out := new(MeterObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeterParameters) DeepCopyInto(out *MeterParameters) {
	*out = *in
	if in.CustomerMapping != nil {
		in, out := &in.CustomerMapping, &out.CustomerMapping
		*out = make([]CustomerMappingParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DefaultAggregation != nil {
		in, out := &in.DefaultAggregation, &out.DefaultAggregation
		*out = make([]DefaultAggregationParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.EventName != nil {
		in, out := &in.EventName, &out.EventName
		*out = new(string)
		**out = **in
	}
	if in.EventTimeWindow != nil {
		in, out := &in.EventTimeWindow, &out.EventTimeWindow
		*out = new(string)
		**out = **in
	}
	if in.ValueSettings != nil {
		in, out := &in.ValueSettings, &out.ValueSettings
		*out = make([]ValueSettingsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeterParameters.
func (in *MeterParameters) DeepCopy() *MeterParameters {
	if in == nil {
		return nil
	}
	out := new(MeterParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeterSpec) DeepCopyInto(out *MeterSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeterSpec.
func (in *MeterSpec) DeepCopy() *MeterSpec {
	if in == nil {
		return nil
	}
	out := new(MeterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeterStatus) DeepCopyInto(out *MeterStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeterStatus.
func (in *MeterStatus) DeepCopy() *MeterStatus {
	if in == nil {
		return nil
	}
	out := new(MeterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValueSettingsInitParameters) DeepCopyInto(out *ValueSettingsInitParameters) {
	*out = *in
	if in.EventPayloadKey != nil {
		in, out := &in.EventPayloadKey, &out.EventPayloadKey
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValueSettingsInitParameters.
func (in *ValueSettingsInitParameters) DeepCopy() *ValueSettingsInitParameters {
	if in == nil {
		return nil
	}
	out := new(ValueSettingsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValueSettingsObservation) DeepCopyInto(out *ValueSettingsObservation) {
	*out = *in
	if in.EventPayloadKey != nil {
		in, out := &in.EventPayloadKey, &out.EventPayloadKey
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValueSettingsObservation.
func (in *ValueSettingsObservation) DeepCopy() *ValueSettingsObservation {
	if in == nil {
		return nil
	}
	out := new(ValueSettingsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ValueSettingsParameters) DeepCopyInto(out *ValueSettingsParameters) {
	*out = *in
	if in.EventPayloadKey != nil {
		in, out := &in.EventPayloadKey, &out.EventPayloadKey
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ValueSettingsParameters.
func (in *ValueSettingsParameters) DeepCopy() *ValueSettingsParameters {
	if in == nil {
		return nil
	}
	out := new(ValueSettingsParameters)
	in.DeepCopyInto(out)
	return out
}
