// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type CustomerMappingInitParameters struct {

	// String. The key in the event payload to use for customer mapping.
	// The key in the usage event payload to use for mapping the event to a customer.
	EventPayloadKey *string `json:"eventPayloadKey,omitempty" tf:"event_payload_key,omitempty"`

	// String. The method for mapping a meter event to a customer. Must be by_id.
	// The method for mapping a meter event to a customer. Must be by_id
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type CustomerMappingObservation struct {

	// String. The key in the event payload to use for customer mapping.
	// The key in the usage event payload to use for mapping the event to a customer.
	EventPayloadKey *string `json:"eventPayloadKey,omitempty" tf:"event_payload_key,omitempty"`

	// String. The method for mapping a meter event to a customer. Must be by_id.
	// The method for mapping a meter event to a customer. Must be by_id
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type CustomerMappingParameters struct {

	// String. The key in the event payload to use for customer mapping.
	// The key in the usage event payload to use for mapping the event to a customer.
	// +kubebuilder:validation:Optional
	EventPayloadKey *string `json:"eventPayloadKey" tf:"event_payload_key,omitempty"`

	// String. The method for mapping a meter event to a customer. Must be by_id.
	// The method for mapping a meter event to a customer. Must be by_id
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type DefaultAggregationInitParameters struct {

	// String. Specifies how events are aggregated. Allowed values are count to count the number of events and sum to sum each event’s value.
	// Specifies how events are aggregated. Allowed values are count to count the number of events and sum to sum each event’s value.
	Formula *string `json:"formula,omitempty" tf:"formula,omitempty"`
}

type DefaultAggregationObservation struct {

	// String. Specifies how events are aggregated. Allowed values are count to count the number of events and sum to sum each event’s value.
	// Specifies how events are aggregated. Allowed values are count to count the number of events and sum to sum each event’s value.
	Formula *string `json:"formula,omitempty" tf:"formula,omitempty"`
}

type DefaultAggregationParameters struct {

	// String. Specifies how events are aggregated. Allowed values are count to count the number of events and sum to sum each event’s value.
	// Specifies how events are aggregated. Allowed values are count to count the number of events and sum to sum each event’s value.
	// +kubebuilder:validation:Optional
	Formula *string `json:"formula" tf:"formula,omitempty"`
}

type MeterInitParameters struct {

	// Lst(Resource). Fields that specify how to map a meter event to a customer.
	// Fields that specify how to map a meter event to a customer.
	CustomerMapping []CustomerMappingInitParameters `json:"customerMapping,omitempty" tf:"customer_mapping,omitempty"`

	// List(Resource). The default settings to aggregate a meter’s events with.
	// The default settings to aggregate a meter’s events with
	DefaultAggregation []DefaultAggregationInitParameters `json:"defaultAggregation,omitempty" tf:"default_aggregation,omitempty"`

	// String. The display name of the meter.
	// The meter’s name.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// String. The name of the meter event to record usage for. Corresponds with the event_name field on meter events.
	// The name of the meter event to record usage for. Corresponds with the event_name field on meter events
	EventName *string `json:"eventName,omitempty" tf:"event_name,omitempty"`

	// String. The time window to pre-aggregate meter events for, if any. Possible values are:
	// The time window to pre-aggregate meter events for, if any.
	EventTimeWindow *string `json:"eventTimeWindow,omitempty" tf:"event_time_window,omitempty"`

	// List(Resource). Fields that specify how to calculate a meter event’s value.
	// Fields that specify how to calculate a meter event’s value.
	ValueSettings []ValueSettingsInitParameters `json:"valueSettings,omitempty" tf:"value_settings,omitempty"`
}

type MeterObservation struct {

	// Lst(Resource). Fields that specify how to map a meter event to a customer.
	// Fields that specify how to map a meter event to a customer.
	CustomerMapping []CustomerMappingObservation `json:"customerMapping,omitempty" tf:"customer_mapping,omitempty"`

	// List(Resource). The default settings to aggregate a meter’s events with.
	// The default settings to aggregate a meter’s events with
	DefaultAggregation []DefaultAggregationObservation `json:"defaultAggregation,omitempty" tf:"default_aggregation,omitempty"`

	// String. The display name of the meter.
	// The meter’s name.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// String. The name of the meter event to record usage for. Corresponds with the event_name field on meter events.
	// The name of the meter event to record usage for. Corresponds with the event_name field on meter events
	EventName *string `json:"eventName,omitempty" tf:"event_name,omitempty"`

	// String. The time window to pre-aggregate meter events for, if any. Possible values are:
	// The time window to pre-aggregate meter events for, if any.
	EventTimeWindow *string `json:"eventTimeWindow,omitempty" tf:"event_time_window,omitempty"`

	// String. The unique identifier for the object.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// List(Resource). Fields that specify how to calculate a meter event’s value.
	// Fields that specify how to calculate a meter event’s value.
	ValueSettings []ValueSettingsObservation `json:"valueSettings,omitempty" tf:"value_settings,omitempty"`
}

type MeterParameters struct {

	// Lst(Resource). Fields that specify how to map a meter event to a customer.
	// Fields that specify how to map a meter event to a customer.
	// +kubebuilder:validation:Optional
	CustomerMapping []CustomerMappingParameters `json:"customerMapping,omitempty" tf:"customer_mapping,omitempty"`

	// List(Resource). The default settings to aggregate a meter’s events with.
	// The default settings to aggregate a meter’s events with
	// +kubebuilder:validation:Optional
	DefaultAggregation []DefaultAggregationParameters `json:"defaultAggregation,omitempty" tf:"default_aggregation,omitempty"`

	// String. The display name of the meter.
	// The meter’s name.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// String. The name of the meter event to record usage for. Corresponds with the event_name field on meter events.
	// The name of the meter event to record usage for. Corresponds with the event_name field on meter events
	// +kubebuilder:validation:Optional
	EventName *string `json:"eventName,omitempty" tf:"event_name,omitempty"`

	// String. The time window to pre-aggregate meter events for, if any. Possible values are:
	// The time window to pre-aggregate meter events for, if any.
	// +kubebuilder:validation:Optional
	EventTimeWindow *string `json:"eventTimeWindow,omitempty" tf:"event_time_window,omitempty"`

	// List(Resource). Fields that specify how to calculate a meter event’s value.
	// Fields that specify how to calculate a meter event’s value.
	// +kubebuilder:validation:Optional
	ValueSettings []ValueSettingsParameters `json:"valueSettings,omitempty" tf:"value_settings,omitempty"`
}

type ValueSettingsInitParameters struct {

	// String. The key in the event payload to use for customer mapping.
	// The key in the usage event payload to use as the value for this meter. For example, if the event payload  contains usage on a bytes_used field, then set the event_payload_key to “bytes_used”
	EventPayloadKey *string `json:"eventPayloadKey,omitempty" tf:"event_payload_key,omitempty"`
}

type ValueSettingsObservation struct {

	// String. The key in the event payload to use for customer mapping.
	// The key in the usage event payload to use as the value for this meter. For example, if the event payload  contains usage on a bytes_used field, then set the event_payload_key to “bytes_used”
	EventPayloadKey *string `json:"eventPayloadKey,omitempty" tf:"event_payload_key,omitempty"`
}

type ValueSettingsParameters struct {

	// String. The key in the event payload to use for customer mapping.
	// The key in the usage event payload to use as the value for this meter. For example, if the event payload  contains usage on a bytes_used field, then set the event_payload_key to “bytes_used”
	// +kubebuilder:validation:Optional
	EventPayloadKey *string `json:"eventPayloadKey" tf:"event_payload_key,omitempty"`
}

// MeterSpec defines the desired state of Meter
type MeterSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     MeterParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MeterInitParameters `json:"initProvider,omitempty"`
}

// MeterStatus defines the observed state of Meter.
type MeterStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        MeterObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Meter is the Schema for the Meters API. The Stripe Meter can be created, modified and configured by this resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,stripe}
type Meter struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.defaultAggregation) || (has(self.initProvider) && has(self.initProvider.defaultAggregation))",message="spec.forProvider.defaultAggregation is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.eventName) || (has(self.initProvider) && has(self.initProvider.eventName))",message="spec.forProvider.eventName is a required parameter"
	Spec   MeterSpec   `json:"spec"`
	Status MeterStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MeterList contains a list of Meters
type MeterList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Meter `json:"items"`
}

// Repository type metadata.
var (
	Meter_Kind             = "Meter"
	Meter_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Meter_Kind}.String()
	Meter_KindAPIVersion   = Meter_Kind + "." + CRDGroupVersion.String()
	Meter_GroupVersionKind = CRDGroupVersion.WithKind(Meter_Kind)
)

func init() {
	SchemeBuilder.Register(&Meter{}, &MeterList{})
}
