// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type CouponInitParameters struct {

	// Int. Amount (in the currency specified) that will be taken off the subtotal of any invoices for this customer.
	// Amount (in the currency specified) that will be taken off the subtotal of any invoices for this customer.
	AmountOff *float64 `json:"amountOff,omitempty" tf:"amount_off,omitempty"`

	// List(String). A list of product IDs this coupon applies to.
	// A list of product IDs this coupon applies to
	AppliesTo []*string `json:"appliesTo,omitempty" tf:"applies_to,omitempty"`

	// String. Unique string of your choice that will be used to identify this coupon when applying it to a customer.
	// Unique string of your choice that will be used to identify this coupon when applying it to a customer. If you don’t want to specify a particular code, you can leave the ID blank and we’ll generate a random code for you.
	CouponID *string `json:"couponId,omitempty" tf:"coupon_id,omitempty"`

	// String. Required if amount_off has been set, the three-letter ISO code for the currency of the amount to take off.
	// If amount_off has been set, the three-letter ISO code for the currency of the amount to take off.
	Currency *string `json:"currency,omitempty" tf:"currency,omitempty"`

	// String. Describes how long a customer who applies this coupon will get the discount. One of forever, once, and repeating.
	// One of forever, once, and repeating. Describes how long a customer who applies this coupon will get the discount.
	Duration *string `json:"duration,omitempty" tf:"duration,omitempty"`

	// If duration is repeating, the number of months the coupon applies. Null if coupon duration is forever or once.
	DurationInMonths *float64 `json:"durationInMonths,omitempty" tf:"duration_in_months,omitempty"`

	// Int. Maximum number of times this coupon can be redeemed, in total, across all customers, before it is no longer valid.
	// Maximum number of times this coupon can be redeemed, in total, across all customers, before it is no longer valid.
	MaxRedemptions *float64 `json:"maxRedemptions,omitempty" tf:"max_redemptions,omitempty"`

	// Map(String). Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
	// Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// String. Name of the coupon displayed to customers on for instance invoices or receipts.
	// Name of the coupon displayed to customers on for instance invoices or receipts.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Float. Percent that will be taken off the subtotal of any invoices for this customer for the duration of the coupon. For example, a coupon with percent_off of 50 will make a $100 invoice $50 instead.
	// Percent that will be taken off the subtotal of any invoices for this customer for the duration of the coupon. For example, a coupon with percent_off of 50 will make a $100 invoice $50 instead.
	PercentOff *float64 `json:"percentOff,omitempty" tf:"percent_off,omitempty"`

	// String. Date after which the coupon can no longer be redeemed. Expected format is in the RFC3339.
	// Date after which the coupon can no longer be redeemed. Expected format is RFC3339
	RedeemBy *string `json:"redeemBy,omitempty" tf:"redeem_by,omitempty"`
}

type CouponObservation struct {

	// Int. Amount (in the currency specified) that will be taken off the subtotal of any invoices for this customer.
	// Amount (in the currency specified) that will be taken off the subtotal of any invoices for this customer.
	AmountOff *float64 `json:"amountOff,omitempty" tf:"amount_off,omitempty"`

	// List(String). A list of product IDs this coupon applies to.
	// A list of product IDs this coupon applies to
	AppliesTo []*string `json:"appliesTo,omitempty" tf:"applies_to,omitempty"`

	// String. Unique string of your choice that will be used to identify this coupon when applying it to a customer.
	// Unique string of your choice that will be used to identify this coupon when applying it to a customer. If you don’t want to specify a particular code, you can leave the ID blank and we’ll generate a random code for you.
	CouponID *string `json:"couponId,omitempty" tf:"coupon_id,omitempty"`

	// String. Required if amount_off has been set, the three-letter ISO code for the currency of the amount to take off.
	// If amount_off has been set, the three-letter ISO code for the currency of the amount to take off.
	Currency *string `json:"currency,omitempty" tf:"currency,omitempty"`

	// String. Describes how long a customer who applies this coupon will get the discount. One of forever, once, and repeating.
	// One of forever, once, and repeating. Describes how long a customer who applies this coupon will get the discount.
	Duration *string `json:"duration,omitempty" tf:"duration,omitempty"`

	// If duration is repeating, the number of months the coupon applies. Null if coupon duration is forever or once.
	DurationInMonths *float64 `json:"durationInMonths,omitempty" tf:"duration_in_months,omitempty"`

	// String. The unique identifier for the object.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Int. Maximum number of times this coupon can be redeemed, in total, across all customers, before it is no longer valid.
	// Maximum number of times this coupon can be redeemed, in total, across all customers, before it is no longer valid.
	MaxRedemptions *float64 `json:"maxRedemptions,omitempty" tf:"max_redemptions,omitempty"`

	// Map(String). Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
	// Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// String. Name of the coupon displayed to customers on for instance invoices or receipts.
	// Name of the coupon displayed to customers on for instance invoices or receipts.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Float. Percent that will be taken off the subtotal of any invoices for this customer for the duration of the coupon. For example, a coupon with percent_off of 50 will make a $100 invoice $50 instead.
	// Percent that will be taken off the subtotal of any invoices for this customer for the duration of the coupon. For example, a coupon with percent_off of 50 will make a $100 invoice $50 instead.
	PercentOff *float64 `json:"percentOff,omitempty" tf:"percent_off,omitempty"`

	// String. Date after which the coupon can no longer be redeemed. Expected format is in the RFC3339.
	// Date after which the coupon can no longer be redeemed. Expected format is RFC3339
	RedeemBy *string `json:"redeemBy,omitempty" tf:"redeem_by,omitempty"`

	// Int. Number of times this coupon has been applied to a customer.
	// Number of times this coupon has been applied to a customer.
	TimesRedeemed *float64 `json:"timesRedeemed,omitempty" tf:"times_redeemed,omitempty"`

	// Bool. Taking account of the above properties, whether this coupon can still be applied to a customer.
	// Taking account of the above properties, whether this coupon can still be applied to a customer.
	Valid *bool `json:"valid,omitempty" tf:"valid,omitempty"`
}

type CouponParameters struct {

	// Int. Amount (in the currency specified) that will be taken off the subtotal of any invoices for this customer.
	// Amount (in the currency specified) that will be taken off the subtotal of any invoices for this customer.
	// +kubebuilder:validation:Optional
	AmountOff *float64 `json:"amountOff,omitempty" tf:"amount_off,omitempty"`

	// List(String). A list of product IDs this coupon applies to.
	// A list of product IDs this coupon applies to
	// +kubebuilder:validation:Optional
	AppliesTo []*string `json:"appliesTo,omitempty" tf:"applies_to,omitempty"`

	// String. Unique string of your choice that will be used to identify this coupon when applying it to a customer.
	// Unique string of your choice that will be used to identify this coupon when applying it to a customer. If you don’t want to specify a particular code, you can leave the ID blank and we’ll generate a random code for you.
	// +kubebuilder:validation:Optional
	CouponID *string `json:"couponId,omitempty" tf:"coupon_id,omitempty"`

	// String. Required if amount_off has been set, the three-letter ISO code for the currency of the amount to take off.
	// If amount_off has been set, the three-letter ISO code for the currency of the amount to take off.
	// +kubebuilder:validation:Optional
	Currency *string `json:"currency,omitempty" tf:"currency,omitempty"`

	// String. Describes how long a customer who applies this coupon will get the discount. One of forever, once, and repeating.
	// One of forever, once, and repeating. Describes how long a customer who applies this coupon will get the discount.
	// +kubebuilder:validation:Optional
	Duration *string `json:"duration,omitempty" tf:"duration,omitempty"`

	// If duration is repeating, the number of months the coupon applies. Null if coupon duration is forever or once.
	// +kubebuilder:validation:Optional
	DurationInMonths *float64 `json:"durationInMonths,omitempty" tf:"duration_in_months,omitempty"`

	// Int. Maximum number of times this coupon can be redeemed, in total, across all customers, before it is no longer valid.
	// Maximum number of times this coupon can be redeemed, in total, across all customers, before it is no longer valid.
	// +kubebuilder:validation:Optional
	MaxRedemptions *float64 `json:"maxRedemptions,omitempty" tf:"max_redemptions,omitempty"`

	// Map(String). Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
	// Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// String. Name of the coupon displayed to customers on for instance invoices or receipts.
	// Name of the coupon displayed to customers on for instance invoices or receipts.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Float. Percent that will be taken off the subtotal of any invoices for this customer for the duration of the coupon. For example, a coupon with percent_off of 50 will make a $100 invoice $50 instead.
	// Percent that will be taken off the subtotal of any invoices for this customer for the duration of the coupon. For example, a coupon with percent_off of 50 will make a $100 invoice $50 instead.
	// +kubebuilder:validation:Optional
	PercentOff *float64 `json:"percentOff,omitempty" tf:"percent_off,omitempty"`

	// String. Date after which the coupon can no longer be redeemed. Expected format is in the RFC3339.
	// Date after which the coupon can no longer be redeemed. Expected format is RFC3339
	// +kubebuilder:validation:Optional
	RedeemBy *string `json:"redeemBy,omitempty" tf:"redeem_by,omitempty"`
}

// CouponSpec defines the desired state of Coupon
type CouponSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     CouponParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CouponInitParameters `json:"initProvider,omitempty"`
}

// CouponStatus defines the observed state of Coupon.
type CouponStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CouponObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Coupon is the Schema for the Coupons API. The Stripe Coupon can be created, modified, configured and removed by this resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,stripe}
type Coupon struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              CouponSpec   `json:"spec"`
	Status            CouponStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CouponList contains a list of Coupons
type CouponList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Coupon `json:"items"`
}

// Repository type metadata.
var (
	Coupon_Kind             = "Coupon"
	Coupon_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Coupon_Kind}.String()
	Coupon_KindAPIVersion   = Coupon_Kind + "." + CRDGroupVersion.String()
	Coupon_GroupVersionKind = CRDGroupVersion.WithKind(Coupon_Kind)
)

func init() {
	SchemeBuilder.Register(&Coupon{}, &CouponList{})
}
