//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Coupon) DeepCopyInto(out *Coupon) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Coupon.
func (in *Coupon) DeepCopy() *Coupon {
	if in == nil {
		return nil
	}
	out := new(Coupon)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Coupon) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouponInitParameters) DeepCopyInto(out *CouponInitParameters) {
	*out = *in
	if in.AmountOff != nil {
		in, out := &in.AmountOff, &out.AmountOff
		*out = new(float64)
		**out = **in
	}
	if in.AppliesTo != nil {
		in, out := &in.AppliesTo, &out.AppliesTo
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CouponID != nil {
		in, out := &in.CouponID, &out.CouponID
		*out = new(string)
		**out = **in
	}
	if in.Currency != nil {
		in, out := &in.Currency, &out.Currency
		*out = new(string)
		**out = **in
	}
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(string)
		**out = **in
	}
	if in.DurationInMonths != nil {
		in, out := &in.DurationInMonths, &out.DurationInMonths
		*out = new(float64)
		**out = **in
	}
	if in.MaxRedemptions != nil {
		in, out := &in.MaxRedemptions, &out.MaxRedemptions
		*out = new(float64)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PercentOff != nil {
		in, out := &in.PercentOff, &out.PercentOff
		*out = new(float64)
		**out = **in
	}
	if in.RedeemBy != nil {
		in, out := &in.RedeemBy, &out.RedeemBy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouponInitParameters.
func (in *CouponInitParameters) DeepCopy() *CouponInitParameters {
	if in == nil {
		return nil
	}
	out := new(CouponInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouponList) DeepCopyInto(out *CouponList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Coupon, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouponList.
func (in *CouponList) DeepCopy() *CouponList {
	if in == nil {
		return nil
	}
	out := new(CouponList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CouponList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouponObservation) DeepCopyInto(out *CouponObservation) {
	*out = *in
	if in.AmountOff != nil {
		in, out := &in.AmountOff, &out.AmountOff
		*out = new(float64)
		**out = **in
	}
	if in.AppliesTo != nil {
		in, out := &in.AppliesTo, &out.AppliesTo
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CouponID != nil {
		in, out := &in.CouponID, &out.CouponID
		*out = new(string)
		**out = **in
	}
	if in.Currency != nil {
		in, out := &in.Currency, &out.Currency
		*out = new(string)
		**out = **in
	}
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(string)
		**out = **in
	}
	if in.DurationInMonths != nil {
		in, out := &in.DurationInMonths, &out.DurationInMonths
		*out = new(float64)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.MaxRedemptions != nil {
		in, out := &in.MaxRedemptions, &out.MaxRedemptions
		*out = new(float64)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PercentOff != nil {
		in, out := &in.PercentOff, &out.PercentOff
		*out = new(float64)
		**out = **in
	}
	if in.RedeemBy != nil {
		in, out := &in.RedeemBy, &out.RedeemBy
		*out = new(string)
		**out = **in
	}
	if in.TimesRedeemed != nil {
		in, out := &in.TimesRedeemed, &out.TimesRedeemed
		*out = new(float64)
		**out = **in
	}
	if in.Valid != nil {
		in, out := &in.Valid, &out.Valid
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouponObservation.
func (in *CouponObservation) DeepCopy() *CouponObservation {
	if in == nil {
		return nil
	}
	out := new(CouponObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouponParameters) DeepCopyInto(out *CouponParameters) {
	*out = *in
	if in.AmountOff != nil {
		in, out := &in.AmountOff, &out.AmountOff
		*out = new(float64)
		**out = **in
	}
	if in.AppliesTo != nil {
		in, out := &in.AppliesTo, &out.AppliesTo
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.CouponID != nil {
		in, out := &in.CouponID, &out.CouponID
		*out = new(string)
		**out = **in
	}
	if in.Currency != nil {
		in, out := &in.Currency, &out.Currency
		*out = new(string)
		**out = **in
	}
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(string)
		**out = **in
	}
	if in.DurationInMonths != nil {
		in, out := &in.DurationInMonths, &out.DurationInMonths
		*out = new(float64)
		**out = **in
	}
	if in.MaxRedemptions != nil {
		in, out := &in.MaxRedemptions, &out.MaxRedemptions
		*out = new(float64)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PercentOff != nil {
		in, out := &in.PercentOff, &out.PercentOff
		*out = new(float64)
		**out = **in
	}
	if in.RedeemBy != nil {
		in, out := &in.RedeemBy, &out.RedeemBy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouponParameters.
func (in *CouponParameters) DeepCopy() *CouponParameters {
	if in == nil {
		return nil
	}
	out := new(CouponParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouponSpec) DeepCopyInto(out *CouponSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouponSpec.
func (in *CouponSpec) DeepCopy() *CouponSpec {
	if in == nil {
		return nil
	}
	out := new(CouponSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CouponStatus) DeepCopyInto(out *CouponStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CouponStatus.
func (in *CouponStatus) DeepCopy() *CouponStatus {
	if in == nil {
		return nil
	}
	out := new(CouponStatus)
	in.DeepCopyInto(out)
	return out
}
