//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CurrencyOptionsInitParameters) DeepCopyInto(out *CurrencyOptionsInitParameters) {
	*out = *in
	if in.Currency != nil {
		in, out := &in.Currency, &out.Currency
		*out = new(string)
		**out = **in
	}
	if in.CustomUnitAmount != nil {
		in, out := &in.CustomUnitAmount, &out.CustomUnitAmount
		*out = make([]CustomUnitAmountInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TaxBehavior != nil {
		in, out := &in.TaxBehavior, &out.TaxBehavior
		*out = new(string)
		**out = **in
	}
	if in.Tiers != nil {
		in, out := &in.Tiers, &out.Tiers
		*out = make([]TiersInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UnitAmount != nil {
		in, out := &in.UnitAmount, &out.UnitAmount
		*out = new(float64)
		**out = **in
	}
	if in.UnitAmountDecimal != nil {
		in, out := &in.UnitAmountDecimal, &out.UnitAmountDecimal
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CurrencyOptionsInitParameters.
func (in *CurrencyOptionsInitParameters) DeepCopy() *CurrencyOptionsInitParameters {
	if in == nil {
		return nil
	}
	out := new(CurrencyOptionsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CurrencyOptionsObservation) DeepCopyInto(out *CurrencyOptionsObservation) {
	*out = *in
	if in.Currency != nil {
		in, out := &in.Currency, &out.Currency
		*out = new(string)
		**out = **in
	}
	if in.CustomUnitAmount != nil {
		in, out := &in.CustomUnitAmount, &out.CustomUnitAmount
		*out = make([]CustomUnitAmountObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TaxBehavior != nil {
		in, out := &in.TaxBehavior, &out.TaxBehavior
		*out = new(string)
		**out = **in
	}
	if in.Tiers != nil {
		in, out := &in.Tiers, &out.Tiers
		*out = make([]TiersObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UnitAmount != nil {
		in, out := &in.UnitAmount, &out.UnitAmount
		*out = new(float64)
		**out = **in
	}
	if in.UnitAmountDecimal != nil {
		in, out := &in.UnitAmountDecimal, &out.UnitAmountDecimal
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CurrencyOptionsObservation.
func (in *CurrencyOptionsObservation) DeepCopy() *CurrencyOptionsObservation {
	if in == nil {
		return nil
	}
	out := new(CurrencyOptionsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CurrencyOptionsParameters) DeepCopyInto(out *CurrencyOptionsParameters) {
	*out = *in
	if in.Currency != nil {
		in, out := &in.Currency, &out.Currency
		*out = new(string)
		**out = **in
	}
	if in.CustomUnitAmount != nil {
		in, out := &in.CustomUnitAmount, &out.CustomUnitAmount
		*out = make([]CustomUnitAmountParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TaxBehavior != nil {
		in, out := &in.TaxBehavior, &out.TaxBehavior
		*out = new(string)
		**out = **in
	}
	if in.Tiers != nil {
		in, out := &in.Tiers, &out.Tiers
		*out = make([]TiersParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UnitAmount != nil {
		in, out := &in.UnitAmount, &out.UnitAmount
		*out = new(float64)
		**out = **in
	}
	if in.UnitAmountDecimal != nil {
		in, out := &in.UnitAmountDecimal, &out.UnitAmountDecimal
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CurrencyOptionsParameters.
func (in *CurrencyOptionsParameters) DeepCopy() *CurrencyOptionsParameters {
	if in == nil {
		return nil
	}
	out := new(CurrencyOptionsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomUnitAmountInitParameters) DeepCopyInto(out *CustomUnitAmountInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Maximum != nil {
		in, out := &in.Maximum, &out.Maximum
		*out = new(float64)
		**out = **in
	}
	if in.Minimum != nil {
		in, out := &in.Minimum, &out.Minimum
		*out = new(float64)
		**out = **in
	}
	if in.Preset != nil {
		in, out := &in.Preset, &out.Preset
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomUnitAmountInitParameters.
func (in *CustomUnitAmountInitParameters) DeepCopy() *CustomUnitAmountInitParameters {
	if in == nil {
		return nil
	}
	out := new(CustomUnitAmountInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomUnitAmountObservation) DeepCopyInto(out *CustomUnitAmountObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Maximum != nil {
		in, out := &in.Maximum, &out.Maximum
		*out = new(float64)
		**out = **in
	}
	if in.Minimum != nil {
		in, out := &in.Minimum, &out.Minimum
		*out = new(float64)
		**out = **in
	}
	if in.Preset != nil {
		in, out := &in.Preset, &out.Preset
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomUnitAmountObservation.
func (in *CustomUnitAmountObservation) DeepCopy() *CustomUnitAmountObservation {
	if in == nil {
		return nil
	}
	out := new(CustomUnitAmountObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomUnitAmountParameters) DeepCopyInto(out *CustomUnitAmountParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Maximum != nil {
		in, out := &in.Maximum, &out.Maximum
		*out = new(float64)
		**out = **in
	}
	if in.Minimum != nil {
		in, out := &in.Minimum, &out.Minimum
		*out = new(float64)
		**out = **in
	}
	if in.Preset != nil {
		in, out := &in.Preset, &out.Preset
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomUnitAmountParameters.
func (in *CustomUnitAmountParameters) DeepCopy() *CustomUnitAmountParameters {
	if in == nil {
		return nil
	}
	out := new(CustomUnitAmountParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Price) DeepCopyInto(out *Price) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Price.
func (in *Price) DeepCopy() *Price {
	if in == nil {
		return nil
	}
	out := new(Price)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Price) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PriceCustomUnitAmountInitParameters) DeepCopyInto(out *PriceCustomUnitAmountInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Maximum != nil {
		in, out := &in.Maximum, &out.Maximum
		*out = new(float64)
		**out = **in
	}
	if in.Minimum != nil {
		in, out := &in.Minimum, &out.Minimum
		*out = new(float64)
		**out = **in
	}
	if in.Preset != nil {
		in, out := &in.Preset, &out.Preset
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PriceCustomUnitAmountInitParameters.
func (in *PriceCustomUnitAmountInitParameters) DeepCopy() *PriceCustomUnitAmountInitParameters {
	if in == nil {
		return nil
	}
	out := new(PriceCustomUnitAmountInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PriceCustomUnitAmountObservation) DeepCopyInto(out *PriceCustomUnitAmountObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Maximum != nil {
		in, out := &in.Maximum, &out.Maximum
		*out = new(float64)
		**out = **in
	}
	if in.Minimum != nil {
		in, out := &in.Minimum, &out.Minimum
		*out = new(float64)
		**out = **in
	}
	if in.Preset != nil {
		in, out := &in.Preset, &out.Preset
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PriceCustomUnitAmountObservation.
func (in *PriceCustomUnitAmountObservation) DeepCopy() *PriceCustomUnitAmountObservation {
	if in == nil {
		return nil
	}
	out := new(PriceCustomUnitAmountObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PriceCustomUnitAmountParameters) DeepCopyInto(out *PriceCustomUnitAmountParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Maximum != nil {
		in, out := &in.Maximum, &out.Maximum
		*out = new(float64)
		**out = **in
	}
	if in.Minimum != nil {
		in, out := &in.Minimum, &out.Minimum
		*out = new(float64)
		**out = **in
	}
	if in.Preset != nil {
		in, out := &in.Preset, &out.Preset
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PriceCustomUnitAmountParameters.
func (in *PriceCustomUnitAmountParameters) DeepCopy() *PriceCustomUnitAmountParameters {
	if in == nil {
		return nil
	}
	out := new(PriceCustomUnitAmountParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PriceInitParameters) DeepCopyInto(out *PriceInitParameters) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.BillingScheme != nil {
		in, out := &in.BillingScheme, &out.BillingScheme
		*out = new(string)
		**out = **in
	}
	if in.Currency != nil {
		in, out := &in.Currency, &out.Currency
		*out = new(string)
		**out = **in
	}
	if in.CurrencyOptions != nil {
		in, out := &in.CurrencyOptions, &out.CurrencyOptions
		*out = make([]CurrencyOptionsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CustomUnitAmount != nil {
		in, out := &in.CustomUnitAmount, &out.CustomUnitAmount
		*out = make([]PriceCustomUnitAmountInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LookupKey != nil {
		in, out := &in.LookupKey, &out.LookupKey
		*out = new(string)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Nickname != nil {
		in, out := &in.Nickname, &out.Nickname
		*out = new(string)
		**out = **in
	}
	if in.Product != nil {
		in, out := &in.Product, &out.Product
		*out = new(string)
		**out = **in
	}
	if in.Recurring != nil {
		in, out := &in.Recurring, &out.Recurring
		*out = make([]RecurringInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TaxBehavior != nil {
		in, out := &in.TaxBehavior, &out.TaxBehavior
		*out = new(string)
		**out = **in
	}
	if in.Tiers != nil {
		in, out := &in.Tiers, &out.Tiers
		*out = make([]PriceTiersInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TiersMode != nil {
		in, out := &in.TiersMode, &out.TiersMode
		*out = new(string)
		**out = **in
	}
	if in.TransferLookupKey != nil {
		in, out := &in.TransferLookupKey, &out.TransferLookupKey
		*out = new(bool)
		**out = **in
	}
	if in.TransformQuantity != nil {
		in, out := &in.TransformQuantity, &out.TransformQuantity
		*out = make([]TransformQuantityInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UnitAmount != nil {
		in, out := &in.UnitAmount, &out.UnitAmount
		*out = new(float64)
		**out = **in
	}
	if in.UnitAmountDecimal != nil {
		in, out := &in.UnitAmountDecimal, &out.UnitAmountDecimal
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PriceInitParameters.
func (in *PriceInitParameters) DeepCopy() *PriceInitParameters {
	if in == nil {
		return nil
	}
	out := new(PriceInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PriceList) DeepCopyInto(out *PriceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Price, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PriceList.
func (in *PriceList) DeepCopy() *PriceList {
	if in == nil {
		return nil
	}
	out := new(PriceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PriceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PriceObservation) DeepCopyInto(out *PriceObservation) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.BillingScheme != nil {
		in, out := &in.BillingScheme, &out.BillingScheme
		*out = new(string)
		**out = **in
	}
	if in.Currency != nil {
		in, out := &in.Currency, &out.Currency
		*out = new(string)
		**out = **in
	}
	if in.CurrencyOptions != nil {
		in, out := &in.CurrencyOptions, &out.CurrencyOptions
		*out = make([]CurrencyOptionsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CustomUnitAmount != nil {
		in, out := &in.CustomUnitAmount, &out.CustomUnitAmount
		*out = make([]PriceCustomUnitAmountObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LookupKey != nil {
		in, out := &in.LookupKey, &out.LookupKey
		*out = new(string)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Nickname != nil {
		in, out := &in.Nickname, &out.Nickname
		*out = new(string)
		**out = **in
	}
	if in.Product != nil {
		in, out := &in.Product, &out.Product
		*out = new(string)
		**out = **in
	}
	if in.Recurring != nil {
		in, out := &in.Recurring, &out.Recurring
		*out = make([]RecurringObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TaxBehavior != nil {
		in, out := &in.TaxBehavior, &out.TaxBehavior
		*out = new(string)
		**out = **in
	}
	if in.Tiers != nil {
		in, out := &in.Tiers, &out.Tiers
		*out = make([]PriceTiersObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TiersMode != nil {
		in, out := &in.TiersMode, &out.TiersMode
		*out = new(string)
		**out = **in
	}
	if in.TransferLookupKey != nil {
		in, out := &in.TransferLookupKey, &out.TransferLookupKey
		*out = new(bool)
		**out = **in
	}
	if in.TransformQuantity != nil {
		in, out := &in.TransformQuantity, &out.TransformQuantity
		*out = make([]TransformQuantityObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.UnitAmount != nil {
		in, out := &in.UnitAmount, &out.UnitAmount
		*out = new(float64)
		**out = **in
	}
	if in.UnitAmountDecimal != nil {
		in, out := &in.UnitAmountDecimal, &out.UnitAmountDecimal
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PriceObservation.
func (in *PriceObservation) DeepCopy() *PriceObservation {
	if in == nil {
		return nil
	}
	out := new(PriceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PriceParameters) DeepCopyInto(out *PriceParameters) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.BillingScheme != nil {
		in, out := &in.BillingScheme, &out.BillingScheme
		*out = new(string)
		**out = **in
	}
	if in.Currency != nil {
		in, out := &in.Currency, &out.Currency
		*out = new(string)
		**out = **in
	}
	if in.CurrencyOptions != nil {
		in, out := &in.CurrencyOptions, &out.CurrencyOptions
		*out = make([]CurrencyOptionsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CustomUnitAmount != nil {
		in, out := &in.CustomUnitAmount, &out.CustomUnitAmount
		*out = make([]PriceCustomUnitAmountParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LookupKey != nil {
		in, out := &in.LookupKey, &out.LookupKey
		*out = new(string)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Nickname != nil {
		in, out := &in.Nickname, &out.Nickname
		*out = new(string)
		**out = **in
	}
	if in.Product != nil {
		in, out := &in.Product, &out.Product
		*out = new(string)
		**out = **in
	}
	if in.Recurring != nil {
		in, out := &in.Recurring, &out.Recurring
		*out = make([]RecurringParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TaxBehavior != nil {
		in, out := &in.TaxBehavior, &out.TaxBehavior
		*out = new(string)
		**out = **in
	}
	if in.Tiers != nil {
		in, out := &in.Tiers, &out.Tiers
		*out = make([]PriceTiersParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TiersMode != nil {
		in, out := &in.TiersMode, &out.TiersMode
		*out = new(string)
		**out = **in
	}
	if in.TransferLookupKey != nil {
		in, out := &in.TransferLookupKey, &out.TransferLookupKey
		*out = new(bool)
		**out = **in
	}
	if in.TransformQuantity != nil {
		in, out := &in.TransformQuantity, &out.TransformQuantity
		*out = make([]TransformQuantityParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UnitAmount != nil {
		in, out := &in.UnitAmount, &out.UnitAmount
		*out = new(float64)
		**out = **in
	}
	if in.UnitAmountDecimal != nil {
		in, out := &in.UnitAmountDecimal, &out.UnitAmountDecimal
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PriceParameters.
func (in *PriceParameters) DeepCopy() *PriceParameters {
	if in == nil {
		return nil
	}
	out := new(PriceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PriceSpec) DeepCopyInto(out *PriceSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PriceSpec.
func (in *PriceSpec) DeepCopy() *PriceSpec {
	if in == nil {
		return nil
	}
	out := new(PriceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PriceStatus) DeepCopyInto(out *PriceStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PriceStatus.
func (in *PriceStatus) DeepCopy() *PriceStatus {
	if in == nil {
		return nil
	}
	out := new(PriceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PriceTiersInitParameters) DeepCopyInto(out *PriceTiersInitParameters) {
	*out = *in
	if in.FlatAmount != nil {
		in, out := &in.FlatAmount, &out.FlatAmount
		*out = new(float64)
		**out = **in
	}
	if in.FlatAmountDecimal != nil {
		in, out := &in.FlatAmountDecimal, &out.FlatAmountDecimal
		*out = new(float64)
		**out = **in
	}
	if in.UnitAmount != nil {
		in, out := &in.UnitAmount, &out.UnitAmount
		*out = new(float64)
		**out = **in
	}
	if in.UnitAmountDecimal != nil {
		in, out := &in.UnitAmountDecimal, &out.UnitAmountDecimal
		*out = new(float64)
		**out = **in
	}
	if in.UpTo != nil {
		in, out := &in.UpTo, &out.UpTo
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PriceTiersInitParameters.
func (in *PriceTiersInitParameters) DeepCopy() *PriceTiersInitParameters {
	if in == nil {
		return nil
	}
	out := new(PriceTiersInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PriceTiersObservation) DeepCopyInto(out *PriceTiersObservation) {
	*out = *in
	if in.FlatAmount != nil {
		in, out := &in.FlatAmount, &out.FlatAmount
		*out = new(float64)
		**out = **in
	}
	if in.FlatAmountDecimal != nil {
		in, out := &in.FlatAmountDecimal, &out.FlatAmountDecimal
		*out = new(float64)
		**out = **in
	}
	if in.UnitAmount != nil {
		in, out := &in.UnitAmount, &out.UnitAmount
		*out = new(float64)
		**out = **in
	}
	if in.UnitAmountDecimal != nil {
		in, out := &in.UnitAmountDecimal, &out.UnitAmountDecimal
		*out = new(float64)
		**out = **in
	}
	if in.UpTo != nil {
		in, out := &in.UpTo, &out.UpTo
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PriceTiersObservation.
func (in *PriceTiersObservation) DeepCopy() *PriceTiersObservation {
	if in == nil {
		return nil
	}
	out := new(PriceTiersObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PriceTiersParameters) DeepCopyInto(out *PriceTiersParameters) {
	*out = *in
	if in.FlatAmount != nil {
		in, out := &in.FlatAmount, &out.FlatAmount
		*out = new(float64)
		**out = **in
	}
	if in.FlatAmountDecimal != nil {
		in, out := &in.FlatAmountDecimal, &out.FlatAmountDecimal
		*out = new(float64)
		**out = **in
	}
	if in.UnitAmount != nil {
		in, out := &in.UnitAmount, &out.UnitAmount
		*out = new(float64)
		**out = **in
	}
	if in.UnitAmountDecimal != nil {
		in, out := &in.UnitAmountDecimal, &out.UnitAmountDecimal
		*out = new(float64)
		**out = **in
	}
	if in.UpTo != nil {
		in, out := &in.UpTo, &out.UpTo
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PriceTiersParameters.
func (in *PriceTiersParameters) DeepCopy() *PriceTiersParameters {
	if in == nil {
		return nil
	}
	out := new(PriceTiersParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecurringInitParameters) DeepCopyInto(out *RecurringInitParameters) {
	*out = *in
	if in.AggregateUsage != nil {
		in, out := &in.AggregateUsage, &out.AggregateUsage
		*out = new(string)
		**out = **in
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(string)
		**out = **in
	}
	if in.IntervalCount != nil {
		in, out := &in.IntervalCount, &out.IntervalCount
		*out = new(float64)
		**out = **in
	}
	if in.Meter != nil {
		in, out := &in.Meter, &out.Meter
		*out = new(string)
		**out = **in
	}
	if in.UsageType != nil {
		in, out := &in.UsageType, &out.UsageType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecurringInitParameters.
func (in *RecurringInitParameters) DeepCopy() *RecurringInitParameters {
	if in == nil {
		return nil
	}
	out := new(RecurringInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecurringObservation) DeepCopyInto(out *RecurringObservation) {
	*out = *in
	if in.AggregateUsage != nil {
		in, out := &in.AggregateUsage, &out.AggregateUsage
		*out = new(string)
		**out = **in
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(string)
		**out = **in
	}
	if in.IntervalCount != nil {
		in, out := &in.IntervalCount, &out.IntervalCount
		*out = new(float64)
		**out = **in
	}
	if in.Meter != nil {
		in, out := &in.Meter, &out.Meter
		*out = new(string)
		**out = **in
	}
	if in.UsageType != nil {
		in, out := &in.UsageType, &out.UsageType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecurringObservation.
func (in *RecurringObservation) DeepCopy() *RecurringObservation {
	if in == nil {
		return nil
	}
	out := new(RecurringObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RecurringParameters) DeepCopyInto(out *RecurringParameters) {
	*out = *in
	if in.AggregateUsage != nil {
		in, out := &in.AggregateUsage, &out.AggregateUsage
		*out = new(string)
		**out = **in
	}
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(string)
		**out = **in
	}
	if in.IntervalCount != nil {
		in, out := &in.IntervalCount, &out.IntervalCount
		*out = new(float64)
		**out = **in
	}
	if in.Meter != nil {
		in, out := &in.Meter, &out.Meter
		*out = new(string)
		**out = **in
	}
	if in.UsageType != nil {
		in, out := &in.UsageType, &out.UsageType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RecurringParameters.
func (in *RecurringParameters) DeepCopy() *RecurringParameters {
	if in == nil {
		return nil
	}
	out := new(RecurringParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TiersInitParameters) DeepCopyInto(out *TiersInitParameters) {
	*out = *in
	if in.FlatAmount != nil {
		in, out := &in.FlatAmount, &out.FlatAmount
		*out = new(float64)
		**out = **in
	}
	if in.FlatAmountDecimal != nil {
		in, out := &in.FlatAmountDecimal, &out.FlatAmountDecimal
		*out = new(float64)
		**out = **in
	}
	if in.UnitAmount != nil {
		in, out := &in.UnitAmount, &out.UnitAmount
		*out = new(float64)
		**out = **in
	}
	if in.UnitAmountDecimal != nil {
		in, out := &in.UnitAmountDecimal, &out.UnitAmountDecimal
		*out = new(float64)
		**out = **in
	}
	if in.UpTo != nil {
		in, out := &in.UpTo, &out.UpTo
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TiersInitParameters.
func (in *TiersInitParameters) DeepCopy() *TiersInitParameters {
	if in == nil {
		return nil
	}
	out := new(TiersInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TiersObservation) DeepCopyInto(out *TiersObservation) {
	*out = *in
	if in.FlatAmount != nil {
		in, out := &in.FlatAmount, &out.FlatAmount
		*out = new(float64)
		**out = **in
	}
	if in.FlatAmountDecimal != nil {
		in, out := &in.FlatAmountDecimal, &out.FlatAmountDecimal
		*out = new(float64)
		**out = **in
	}
	if in.UnitAmount != nil {
		in, out := &in.UnitAmount, &out.UnitAmount
		*out = new(float64)
		**out = **in
	}
	if in.UnitAmountDecimal != nil {
		in, out := &in.UnitAmountDecimal, &out.UnitAmountDecimal
		*out = new(float64)
		**out = **in
	}
	if in.UpTo != nil {
		in, out := &in.UpTo, &out.UpTo
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TiersObservation.
func (in *TiersObservation) DeepCopy() *TiersObservation {
	if in == nil {
		return nil
	}
	out := new(TiersObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TiersParameters) DeepCopyInto(out *TiersParameters) {
	*out = *in
	if in.FlatAmount != nil {
		in, out := &in.FlatAmount, &out.FlatAmount
		*out = new(float64)
		**out = **in
	}
	if in.FlatAmountDecimal != nil {
		in, out := &in.FlatAmountDecimal, &out.FlatAmountDecimal
		*out = new(float64)
		**out = **in
	}
	if in.UnitAmount != nil {
		in, out := &in.UnitAmount, &out.UnitAmount
		*out = new(float64)
		**out = **in
	}
	if in.UnitAmountDecimal != nil {
		in, out := &in.UnitAmountDecimal, &out.UnitAmountDecimal
		*out = new(float64)
		**out = **in
	}
	if in.UpTo != nil {
		in, out := &in.UpTo, &out.UpTo
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TiersParameters.
func (in *TiersParameters) DeepCopy() *TiersParameters {
	if in == nil {
		return nil
	}
	out := new(TiersParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransformQuantityInitParameters) DeepCopyInto(out *TransformQuantityInitParameters) {
	*out = *in
	if in.DivideBy != nil {
		in, out := &in.DivideBy, &out.DivideBy
		*out = new(float64)
		**out = **in
	}
	if in.Round != nil {
		in, out := &in.Round, &out.Round
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransformQuantityInitParameters.
func (in *TransformQuantityInitParameters) DeepCopy() *TransformQuantityInitParameters {
	if in == nil {
		return nil
	}
	out := new(TransformQuantityInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransformQuantityObservation) DeepCopyInto(out *TransformQuantityObservation) {
	*out = *in
	if in.DivideBy != nil {
		in, out := &in.DivideBy, &out.DivideBy
		*out = new(float64)
		**out = **in
	}
	if in.Round != nil {
		in, out := &in.Round, &out.Round
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransformQuantityObservation.
func (in *TransformQuantityObservation) DeepCopy() *TransformQuantityObservation {
	if in == nil {
		return nil
	}
	out := new(TransformQuantityObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransformQuantityParameters) DeepCopyInto(out *TransformQuantityParameters) {
	*out = *in
	if in.DivideBy != nil {
		in, out := &in.DivideBy, &out.DivideBy
		*out = new(float64)
		**out = **in
	}
	if in.Round != nil {
		in, out := &in.Round, &out.Round
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransformQuantityParameters.
func (in *TransformQuantityParameters) DeepCopy() *TransformQuantityParameters {
	if in == nil {
		return nil
	}
	out := new(TransformQuantityParameters)
	in.DeepCopyInto(out)
	return out
}
