// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

// Package namespaced contains Kubernetes API for the provider.
package namespaced

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1alpha1 "github.com/valkiriaaquatica/provider-stripe/apis/namespaced/stripecard/v1alpha1"
	v1alpha1stripecoupon "github.com/valkiriaaquatica/provider-stripe/apis/namespaced/stripecoupon/v1alpha1"
	v1alpha1stripecustomer "github.com/valkiriaaquatica/provider-stripe/apis/namespaced/stripecustomer/v1alpha1"
	v1alpha1stripeentitlementsfeature "github.com/valkiriaaquatica/provider-stripe/apis/namespaced/stripeentitlementsfeature/v1alpha1"
	v1alpha1stripefile "github.com/valkiriaaquatica/provider-stripe/apis/namespaced/stripefile/v1alpha1"
	v1alpha1stripemeter "github.com/valkiriaaquatica/provider-stripe/apis/namespaced/stripemeter/v1alpha1"
	v1alpha1stripeportalconfiguration "github.com/valkiriaaquatica/provider-stripe/apis/namespaced/stripeportalconfiguration/v1alpha1"
	v1alpha1stripeprice "github.com/valkiriaaquatica/provider-stripe/apis/namespaced/stripeprice/v1alpha1"
	v1alpha1stripeproduct "github.com/valkiriaaquatica/provider-stripe/apis/namespaced/stripeproduct/v1alpha1"
	v1alpha1stripeproductfeature "github.com/valkiriaaquatica/provider-stripe/apis/namespaced/stripeproductfeature/v1alpha1"
	v1alpha1stripepromotioncode "github.com/valkiriaaquatica/provider-stripe/apis/namespaced/stripepromotioncode/v1alpha1"
	v1alpha1stripeshippingrate "github.com/valkiriaaquatica/provider-stripe/apis/namespaced/stripeshippingrate/v1alpha1"
	v1alpha1stripetaxrate "github.com/valkiriaaquatica/provider-stripe/apis/namespaced/stripetaxrate/v1alpha1"
	v1alpha1namespaced "github.com/valkiriaaquatica/provider-stripe/apis/namespaced/v1alpha1"
	v1beta1 "github.com/valkiriaaquatica/provider-stripe/apis/namespaced/v1beta1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1alpha1stripecoupon.SchemeBuilder.AddToScheme,
		v1alpha1stripecustomer.SchemeBuilder.AddToScheme,
		v1alpha1stripeentitlementsfeature.SchemeBuilder.AddToScheme,
		v1alpha1stripefile.SchemeBuilder.AddToScheme,
		v1alpha1stripemeter.SchemeBuilder.AddToScheme,
		v1alpha1stripeportalconfiguration.SchemeBuilder.AddToScheme,
		v1alpha1stripeprice.SchemeBuilder.AddToScheme,
		v1alpha1stripeproduct.SchemeBuilder.AddToScheme,
		v1alpha1stripeproductfeature.SchemeBuilder.AddToScheme,
		v1alpha1stripepromotioncode.SchemeBuilder.AddToScheme,
		v1alpha1stripeshippingrate.SchemeBuilder.AddToScheme,
		v1alpha1stripetaxrate.SchemeBuilder.AddToScheme,
		v1alpha1namespaced.SchemeBuilder.AddToScheme,
		v1beta1.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
