// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type FileInitParameters struct {

	// String.
	// A content file to upload encoded by base64.
	Base64Content *string `json:"base64content,omitempty" tf:"base64content,omitempty"`

	// String. The suitable name for saving the file to a filesystem.
	// The suitable name for saving the file to a filesystem.
	Filename *string `json:"filename,omitempty" tf:"filename,omitempty"`

	// Optional parameters that automatically create a file link for the newly created file.
	LinkData []LinkDataInitParameters `json:"linkData,omitempty" tf:"link_data,omitempty"`

	// String. The purpose of the uploaded file. One of these values are accepted: account_requirement,
	// additional_verification, business_icon, business_logo, customer_signature, dispute_evidence,
	// document_provider_identity_document, finance_report_run, identity_document, identity_document_downloadable,
	// pci_document, selfie, sigma_scheduled_query, tax_document_user_upload, terminal_reader_splashscreen
	// The purpose of the uploaded file.
	Purpose *string `json:"purpose,omitempty" tf:"purpose,omitempty"`
}

type FileObservation struct {

	// String.
	// A content file to upload encoded by base64.
	Base64Content *string `json:"base64content,omitempty" tf:"base64content,omitempty"`

	// Int. Time at which the object was created. Measured in seconds since the Unix epoch.
	// Time at which the object was created. Measured in seconds since the Unix epoch.
	Created *float64 `json:"created,omitempty" tf:"created,omitempty"`

	// Int. The link isn’t available after this future timestamp.
	// The file expires and isn’t available at this time in epoch seconds.
	ExpiresAt *float64 `json:"expiresAt,omitempty" tf:"expires_at,omitempty"`

	// String. The suitable name for saving the file to a filesystem.
	// The suitable name for saving the file to a filesystem.
	Filename *string `json:"filename,omitempty" tf:"filename,omitempty"`

	// String. The unique identifier for the object.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Optional parameters that automatically create a file link for the newly created file.
	LinkData []LinkDataObservation `json:"linkData,omitempty" tf:"link_data,omitempty"`

	// List(Resource). A list of file links that point at this file.
	// Please see details of links.
	Links []LinksObservation `json:"links,omitempty" tf:"links,omitempty"`

	// String. String representing the object’s type. Objects of the same type share the same value.
	// String representing the object’s type. Objects of the same type share the same value.
	Object *string `json:"object,omitempty" tf:"object,omitempty"`

	// String. The purpose of the uploaded file. One of these values are accepted: account_requirement,
	// additional_verification, business_icon, business_logo, customer_signature, dispute_evidence,
	// document_provider_identity_document, finance_report_run, identity_document, identity_document_downloadable,
	// pci_document, selfie, sigma_scheduled_query, tax_document_user_upload, terminal_reader_splashscreen
	// The purpose of the uploaded file.
	Purpose *string `json:"purpose,omitempty" tf:"purpose,omitempty"`

	// Int. The size of the file object in bytes.
	// The size of the file object in bytes.
	Size *float64 `json:"size,omitempty" tf:"size,omitempty"`

	// String. The returned file type (for example, csv, pdf, jpg, or png).
	// The returned file type (for example, csv, pdf, jpg, or png).
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// String. Use your live secret API key to download the file from this URL.
	// Use your live secret API key to download the file from this URL.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type FileParameters struct {

	// String.
	// A content file to upload encoded by base64.
	// +kubebuilder:validation:Optional
	Base64Content *string `json:"base64content,omitempty" tf:"base64content,omitempty"`

	// String. The suitable name for saving the file to a filesystem.
	// The suitable name for saving the file to a filesystem.
	// +kubebuilder:validation:Optional
	Filename *string `json:"filename,omitempty" tf:"filename,omitempty"`

	// Optional parameters that automatically create a file link for the newly created file.
	// +kubebuilder:validation:Optional
	LinkData []LinkDataParameters `json:"linkData,omitempty" tf:"link_data,omitempty"`

	// String. The purpose of the uploaded file. One of these values are accepted: account_requirement,
	// additional_verification, business_icon, business_logo, customer_signature, dispute_evidence,
	// document_provider_identity_document, finance_report_run, identity_document, identity_document_downloadable,
	// pci_document, selfie, sigma_scheduled_query, tax_document_user_upload, terminal_reader_splashscreen
	// The purpose of the uploaded file.
	// +kubebuilder:validation:Optional
	Purpose *string `json:"purpose,omitempty" tf:"purpose,omitempty"`
}

type LinkDataInitParameters struct {

	// Bool. Set this to true to create a file link for the newly created file.
	// Creating a link is only possible when the file’s purpose is one of the following: business_icon, business_logo,
	// customer_signature, dispute_evidence, pci_document, tax_document_user_upload, or terminal_reader_splashscreen.
	// Set this to true to create a file link for the newly created file. Creating a link is only possible when the file’s purpose is one of the following: business_icon, business_logo, customer_signature, dispute_evidence, pci_document, tax_document_user_upload, or terminal_reader_splashscreen.
	Create *bool `json:"create,omitempty" tf:"create,omitempty"`

	// Int. The link isn’t available after this future timestamp.
	// The link isn’t available after this future timestamp.
	ExpiresAt *float64 `json:"expiresAt,omitempty" tf:"expires_at,omitempty"`

	// Map(String). Set of key-value pairs that you can attach to an object.
	// This can be useful for storing additional information about the object in a structured format.
	// Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`
}

type LinkDataObservation struct {

	// Bool. Set this to true to create a file link for the newly created file.
	// Creating a link is only possible when the file’s purpose is one of the following: business_icon, business_logo,
	// customer_signature, dispute_evidence, pci_document, tax_document_user_upload, or terminal_reader_splashscreen.
	// Set this to true to create a file link for the newly created file. Creating a link is only possible when the file’s purpose is one of the following: business_icon, business_logo, customer_signature, dispute_evidence, pci_document, tax_document_user_upload, or terminal_reader_splashscreen.
	Create *bool `json:"create,omitempty" tf:"create,omitempty"`

	// Int. The link isn’t available after this future timestamp.
	// The link isn’t available after this future timestamp.
	ExpiresAt *float64 `json:"expiresAt,omitempty" tf:"expires_at,omitempty"`

	// Map(String). Set of key-value pairs that you can attach to an object.
	// This can be useful for storing additional information about the object in a structured format.
	// Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`
}

type LinkDataParameters struct {

	// Bool. Set this to true to create a file link for the newly created file.
	// Creating a link is only possible when the file’s purpose is one of the following: business_icon, business_logo,
	// customer_signature, dispute_evidence, pci_document, tax_document_user_upload, or terminal_reader_splashscreen.
	// Set this to true to create a file link for the newly created file. Creating a link is only possible when the file’s purpose is one of the following: business_icon, business_logo, customer_signature, dispute_evidence, pci_document, tax_document_user_upload, or terminal_reader_splashscreen.
	// +kubebuilder:validation:Optional
	Create *bool `json:"create" tf:"create,omitempty"`

	// Int. The link isn’t available after this future timestamp.
	// The link isn’t available after this future timestamp.
	// +kubebuilder:validation:Optional
	ExpiresAt *float64 `json:"expiresAt,omitempty" tf:"expires_at,omitempty"`

	// Map(String). Set of key-value pairs that you can attach to an object.
	// This can be useful for storing additional information about the object in a structured format.
	// Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`
}

type LinksInitParameters struct {
}

type LinksObservation struct {

	// Int. Time at which the object was created. Measured in seconds since the Unix epoch.
	Created *float64 `json:"created,omitempty" tf:"created,omitempty"`

	// Bool. Returns if the link is already expired.
	Expired *bool `json:"expired,omitempty" tf:"expired,omitempty"`

	// Int. The link isn’t available after this future timestamp.
	ExpiresAt *float64 `json:"expiresAt,omitempty" tf:"expires_at,omitempty"`

	// String. The unique identifier for the object.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Bool. Has the value true if the object exists in live mode or the value false
	// if the object exists in test mode.
	Livemode *bool `json:"livemode,omitempty" tf:"livemode,omitempty"`

	// Map(String). Set of key-value pairs that you can attach to an object.
	// This can be useful for storing additional information about the object in a structured format.
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// String. String representing the object’s type. Objects of the same type share the same value.
	Object *string `json:"object,omitempty" tf:"object,omitempty"`

	// String. Use your live secret API key to download the file from this URL.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`
}

type LinksParameters struct {
}

// FileSpec defines the desired state of File
type FileSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            FileParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider FileInitParameters `json:"initProvider,omitempty"`
}

// FileStatus defines the observed state of File.
type FileStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        FileObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// File is the Schema for the Files API. The Stripe File can be created by this resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,stripe}
type File struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.base64content) || (has(self.initProvider) && has(self.initProvider.base64content))",message="spec.forProvider.base64content is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.filename) || (has(self.initProvider) && has(self.initProvider.filename))",message="spec.forProvider.filename is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.purpose) || (has(self.initProvider) && has(self.initProvider.purpose))",message="spec.forProvider.purpose is a required parameter"
	Spec   FileSpec   `json:"spec"`
	Status FileStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// FileList contains a list of Files
type FileList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []File `json:"items"`
}

// Repository type metadata.
var (
	File_Kind             = "File"
	File_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: File_Kind}.String()
	File_KindAPIVersion   = File_Kind + "." + CRDGroupVersion.String()
	File_GroupVersionKind = CRDGroupVersion.WithKind(File_Kind)
)

func init() {
	SchemeBuilder.Register(&File{}, &FileList{})
}
