// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type CardInitParameters struct {

	// Map(String). Address map with fields related to the address: line1, line2, city, state
	// , zip and country.
	// Address map with fields related to the address: line1, line2, city, state, zip and country
	// +mapType=granular
	Address map[string]*string `json:"address,omitempty" tf:"address,omitempty"`

	// String. The customer that this card belongs to.
	// The customer that this card belongs to.
	Customer *string `json:"customer,omitempty" tf:"customer,omitempty"`

	// Int. Card security code. Highly recommended to always include this value, but it's required only
	// for accounts based in European countries.
	// Card security code. Highly recommended to always include this value, but it's required only for accounts based in European countries.
	CvcSecretRef *v1.SecretKeySelector `json:"cvcSecretRef,omitempty" tf:"-"`

	// Int. Number representing the card's expiration month.
	// Two-digit number representing the card's expiration month.
	ExpMonth *float64 `json:"expMonth,omitempty" tf:"exp_month,omitempty"`

	// Int. Four-digit number representing the card's expiration year.
	// Four-digit number representing the card's expiration year.
	ExpYear *float64 `json:"expYear,omitempty" tf:"exp_year,omitempty"`

	// Map(String). Set of key-value pairs that you can attach to an object. This can be useful for
	// storing additional information about the object in a structured format.
	// Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// String. Cardholder name.
	// Cardholder name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// String. The card number, as a string without any separators.
	// The card number, as a string without any separators.
	NumberSecretRef v1.SecretKeySelector `json:"numberSecretRef" tf:"-"`
}

type CardObservation struct {

	// Map(String). Address map with fields related to the address: line1, line2, city, state
	// , zip and country.
	// Address map with fields related to the address: line1, line2, city, state, zip and country
	// +mapType=granular
	Address map[string]*string `json:"address,omitempty" tf:"address,omitempty"`

	// String. If address line1 was provided, results of the check: pass, fail, unavailable,
	// or unchecked.
	// If address_line1 was provided, results of the check: pass, fail, unavailable, or unchecked.
	AddressLine1Check *string `json:"addressLine1Check,omitempty" tf:"address_line1_check,omitempty"`

	// String. If address zip was provided, results of the check: pass, fail, unavailable,
	// or unchecked.
	// If address_zip was provided, results of the check: pass, fail, unavailable, or unchecked.
	AddressZipCheck *string `json:"addressZipCheck,omitempty" tf:"address_zip_check,omitempty"`

	// List(String). A set of available payout methods for this card. Only values from this set
	// should be passed as the method when creating a payout.
	// A set of available payout methods for this card. Only values from this set should be passed as the method when creating a payout.
	AvailablePayoutMethods []*string `json:"availablePayoutMethods,omitempty" tf:"available_payout_methods,omitempty"`

	// String. Card brand. Can be American Express, Diners Club, Discover, JCB, MasterCard, UnionPay
	// , Visa, or Unknown.
	// Card brand. Can be American Express, Diners Club, Discover, JCB, MasterCard, UnionPay, Visa, or Unknown.
	Brand *string `json:"brand,omitempty" tf:"brand,omitempty"`

	// String. Two-letter ISO code representing the country of the card. You could use this attribute to get a
	// sense of the international breakdown of cards you’ve collected.
	// Two-letter ISO code representing the country of the card. You could use this attribute to get a sense of the international breakdown of cards you’ve collected.
	Country *string `json:"country,omitempty" tf:"country,omitempty"`

	// String. The customer that this card belongs to.
	// The customer that this card belongs to.
	Customer *string `json:"customer,omitempty" tf:"customer,omitempty"`

	// String. If a cvc was provided, results of the check: pass, fail, unavailable, or unchecked. A
	// result of unchecked indicates that CVC was provided but hasn’t been checked yet
	// If a CVC was provided, results of the check: pass, fail, unavailable, or unchecked. A result of unchecked indicates that CVC was provided but hasn’t been checked yet.
	CvcCheck *string `json:"cvcCheck,omitempty" tf:"cvc_check,omitempty"`

	// Int. Number representing the card's expiration month.
	// Two-digit number representing the card's expiration month.
	ExpMonth *float64 `json:"expMonth,omitempty" tf:"exp_month,omitempty"`

	// Int. Four-digit number representing the card's expiration year.
	// Four-digit number representing the card's expiration year.
	ExpYear *float64 `json:"expYear,omitempty" tf:"exp_year,omitempty"`

	// String. Uniquely identifies this particular card number. You can use this attribute to check whether
	// two customers who’ve signed up with you are using the same card number, for example. For payment methods that tokenize
	// card information (Apple Pay, Google Pay), the tokenized number might be provided instead of the underlying card
	// number.
	// Uniquely identifies this particular card number. You can use this attribute to check whether two customers who’ve signed up with you are using the same card number, for example. For payment methods that tokenize card information (Apple Pay, Google Pay), the tokenized number might be provided instead of the underlying card number.
	Fingerprint *string `json:"fingerprint,omitempty" tf:"fingerprint,omitempty"`

	// String. Card funding type. Can be credit, debit, prepaid, or unknown.
	// Card funding type. Can be credit, debit, prepaid, or unknown.
	Funding *string `json:"funding,omitempty" tf:"funding,omitempty"`

	// String. The unique identifier for the object.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// String. The last four digits of the card.
	// The last four digits of the card.
	Last4 *string `json:"last4,omitempty" tf:"last4,omitempty"`

	// Map(String). Set of key-value pairs that you can attach to an object. This can be useful for
	// storing additional information about the object in a structured format.
	// Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// String. Cardholder name.
	// Cardholder name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// String. If the card number is tokenized, this is the method that was used. Can
	// be android_pay (includes Google Pay), apple_pay, masterpass, visa_checkout, or null.
	// If the card number is tokenized, this is the method that was used. Can be android_pay (includes Google Pay), apple_pay, masterpass, visa_checkout, or null.
	TokenizationMethod *string `json:"tokenizationMethod,omitempty" tf:"tokenization_method,omitempty"`
}

type CardParameters struct {

	// Map(String). Address map with fields related to the address: line1, line2, city, state
	// , zip and country.
	// Address map with fields related to the address: line1, line2, city, state, zip and country
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Address map[string]*string `json:"address,omitempty" tf:"address,omitempty"`

	// String. The customer that this card belongs to.
	// The customer that this card belongs to.
	// +kubebuilder:validation:Optional
	Customer *string `json:"customer,omitempty" tf:"customer,omitempty"`

	// Int. Card security code. Highly recommended to always include this value, but it's required only
	// for accounts based in European countries.
	// Card security code. Highly recommended to always include this value, but it's required only for accounts based in European countries.
	// +kubebuilder:validation:Optional
	CvcSecretRef *v1.SecretKeySelector `json:"cvcSecretRef,omitempty" tf:"-"`

	// Int. Number representing the card's expiration month.
	// Two-digit number representing the card's expiration month.
	// +kubebuilder:validation:Optional
	ExpMonth *float64 `json:"expMonth,omitempty" tf:"exp_month,omitempty"`

	// Int. Four-digit number representing the card's expiration year.
	// Four-digit number representing the card's expiration year.
	// +kubebuilder:validation:Optional
	ExpYear *float64 `json:"expYear,omitempty" tf:"exp_year,omitempty"`

	// Map(String). Set of key-value pairs that you can attach to an object. This can be useful for
	// storing additional information about the object in a structured format.
	// Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// String. Cardholder name.
	// Cardholder name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// String. The card number, as a string without any separators.
	// The card number, as a string without any separators.
	// +kubebuilder:validation:Optional
	NumberSecretRef v1.SecretKeySelector `json:"numberSecretRef" tf:"-"`
}

// CardSpec defines the desired state of Card
type CardSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     CardParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CardInitParameters `json:"initProvider,omitempty"`
}

// CardStatus defines the observed state of Card.
type CardStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CardObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Card is the Schema for the Cards API. The Stripe Card can be created, modified, configured and removed by this resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,stripe}
type Card struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.customer) || (has(self.initProvider) && has(self.initProvider.customer))",message="spec.forProvider.customer is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.expMonth) || (has(self.initProvider) && has(self.initProvider.expMonth))",message="spec.forProvider.expMonth is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.expYear) || (has(self.initProvider) && has(self.initProvider.expYear))",message="spec.forProvider.expYear is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.numberSecretRef)",message="spec.forProvider.numberSecretRef is a required parameter"
	Spec   CardSpec   `json:"spec"`
	Status CardStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CardList contains a list of Cards
type CardList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Card `json:"items"`
}

// Repository type metadata.
var (
	Card_Kind             = "Card"
	Card_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Card_Kind}.String()
	Card_KindAPIVersion   = Card_Kind + "." + CRDGroupVersion.String()
	Card_GroupVersionKind = CRDGroupVersion.WithKind(Card_Kind)
)

func init() {
	SchemeBuilder.Register(&Card{}, &CardList{})
}
