//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Card) DeepCopyInto(out *Card) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Card.
func (in *Card) DeepCopy() *Card {
	if in == nil {
		return nil
	}
	out := new(Card)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Card) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardInitParameters) DeepCopyInto(out *CardInitParameters) {
	*out = *in
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Customer != nil {
		in, out := &in.Customer, &out.Customer
		*out = new(string)
		**out = **in
	}
	if in.CvcSecretRef != nil {
		in, out := &in.CvcSecretRef, &out.CvcSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.ExpMonth != nil {
		in, out := &in.ExpMonth, &out.ExpMonth
		*out = new(float64)
		**out = **in
	}
	if in.ExpYear != nil {
		in, out := &in.ExpYear, &out.ExpYear
		*out = new(float64)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	in.NumberSecretRef.DeepCopyInto(&out.NumberSecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardInitParameters.
func (in *CardInitParameters) DeepCopy() *CardInitParameters {
	if in == nil {
		return nil
	}
	out := new(CardInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardList) DeepCopyInto(out *CardList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Card, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardList.
func (in *CardList) DeepCopy() *CardList {
	if in == nil {
		return nil
	}
	out := new(CardList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CardList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardObservation) DeepCopyInto(out *CardObservation) {
	*out = *in
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.AddressLine1Check != nil {
		in, out := &in.AddressLine1Check, &out.AddressLine1Check
		*out = new(string)
		**out = **in
	}
	if in.AddressZipCheck != nil {
		in, out := &in.AddressZipCheck, &out.AddressZipCheck
		*out = new(string)
		**out = **in
	}
	if in.AvailablePayoutMethods != nil {
		in, out := &in.AvailablePayoutMethods, &out.AvailablePayoutMethods
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Brand != nil {
		in, out := &in.Brand, &out.Brand
		*out = new(string)
		**out = **in
	}
	if in.Country != nil {
		in, out := &in.Country, &out.Country
		*out = new(string)
		**out = **in
	}
	if in.Customer != nil {
		in, out := &in.Customer, &out.Customer
		*out = new(string)
		**out = **in
	}
	if in.CvcCheck != nil {
		in, out := &in.CvcCheck, &out.CvcCheck
		*out = new(string)
		**out = **in
	}
	if in.ExpMonth != nil {
		in, out := &in.ExpMonth, &out.ExpMonth
		*out = new(float64)
		**out = **in
	}
	if in.ExpYear != nil {
		in, out := &in.ExpYear, &out.ExpYear
		*out = new(float64)
		**out = **in
	}
	if in.Fingerprint != nil {
		in, out := &in.Fingerprint, &out.Fingerprint
		*out = new(string)
		**out = **in
	}
	if in.Funding != nil {
		in, out := &in.Funding, &out.Funding
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Last4 != nil {
		in, out := &in.Last4, &out.Last4
		*out = new(string)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.TokenizationMethod != nil {
		in, out := &in.TokenizationMethod, &out.TokenizationMethod
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardObservation.
func (in *CardObservation) DeepCopy() *CardObservation {
	if in == nil {
		return nil
	}
	out := new(CardObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardParameters) DeepCopyInto(out *CardParameters) {
	*out = *in
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Customer != nil {
		in, out := &in.Customer, &out.Customer
		*out = new(string)
		**out = **in
	}
	if in.CvcSecretRef != nil {
		in, out := &in.CvcSecretRef, &out.CvcSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.ExpMonth != nil {
		in, out := &in.ExpMonth, &out.ExpMonth
		*out = new(float64)
		**out = **in
	}
	if in.ExpYear != nil {
		in, out := &in.ExpYear, &out.ExpYear
		*out = new(float64)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	in.NumberSecretRef.DeepCopyInto(&out.NumberSecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardParameters.
func (in *CardParameters) DeepCopy() *CardParameters {
	if in == nil {
		return nil
	}
	out := new(CardParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardSpec) DeepCopyInto(out *CardSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardSpec.
func (in *CardSpec) DeepCopy() *CardSpec {
	if in == nil {
		return nil
	}
	out := new(CardSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CardStatus) DeepCopyInto(out *CardStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CardStatus.
func (in *CardStatus) DeepCopy() *CardStatus {
	if in == nil {
		return nil
	}
	out := new(CardStatus)
	in.DeepCopyInto(out)
	return out
}
