//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CurrencyOptionInitParameters) DeepCopyInto(out *CurrencyOptionInitParameters) {
	*out = *in
	if in.Amount != nil {
		in, out := &in.Amount, &out.Amount
		*out = new(float64)
		**out = **in
	}
	if in.Currency != nil {
		in, out := &in.Currency, &out.Currency
		*out = new(string)
		**out = **in
	}
	if in.TaxBehavior != nil {
		in, out := &in.TaxBehavior, &out.TaxBehavior
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CurrencyOptionInitParameters.
func (in *CurrencyOptionInitParameters) DeepCopy() *CurrencyOptionInitParameters {
	if in == nil {
		return nil
	}
	out := new(CurrencyOptionInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CurrencyOptionObservation) DeepCopyInto(out *CurrencyOptionObservation) {
	*out = *in
	if in.Amount != nil {
		in, out := &in.Amount, &out.Amount
		*out = new(float64)
		**out = **in
	}
	if in.Currency != nil {
		in, out := &in.Currency, &out.Currency
		*out = new(string)
		**out = **in
	}
	if in.TaxBehavior != nil {
		in, out := &in.TaxBehavior, &out.TaxBehavior
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CurrencyOptionObservation.
func (in *CurrencyOptionObservation) DeepCopy() *CurrencyOptionObservation {
	if in == nil {
		return nil
	}
	out := new(CurrencyOptionObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CurrencyOptionParameters) DeepCopyInto(out *CurrencyOptionParameters) {
	*out = *in
	if in.Amount != nil {
		in, out := &in.Amount, &out.Amount
		*out = new(float64)
		**out = **in
	}
	if in.Currency != nil {
		in, out := &in.Currency, &out.Currency
		*out = new(string)
		**out = **in
	}
	if in.TaxBehavior != nil {
		in, out := &in.TaxBehavior, &out.TaxBehavior
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CurrencyOptionParameters.
func (in *CurrencyOptionParameters) DeepCopy() *CurrencyOptionParameters {
	if in == nil {
		return nil
	}
	out := new(CurrencyOptionParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeliveryEstimateInitParameters) DeepCopyInto(out *DeliveryEstimateInitParameters) {
	*out = *in
	if in.Maximum != nil {
		in, out := &in.Maximum, &out.Maximum
		*out = make([]MaximumInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Minimum != nil {
		in, out := &in.Minimum, &out.Minimum
		*out = make([]MinimumInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeliveryEstimateInitParameters.
func (in *DeliveryEstimateInitParameters) DeepCopy() *DeliveryEstimateInitParameters {
	if in == nil {
		return nil
	}
	out := new(DeliveryEstimateInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeliveryEstimateObservation) DeepCopyInto(out *DeliveryEstimateObservation) {
	*out = *in
	if in.Maximum != nil {
		in, out := &in.Maximum, &out.Maximum
		*out = make([]MaximumObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Minimum != nil {
		in, out := &in.Minimum, &out.Minimum
		*out = make([]MinimumObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeliveryEstimateObservation.
func (in *DeliveryEstimateObservation) DeepCopy() *DeliveryEstimateObservation {
	if in == nil {
		return nil
	}
	out := new(DeliveryEstimateObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeliveryEstimateParameters) DeepCopyInto(out *DeliveryEstimateParameters) {
	*out = *in
	if in.Maximum != nil {
		in, out := &in.Maximum, &out.Maximum
		*out = make([]MaximumParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Minimum != nil {
		in, out := &in.Minimum, &out.Minimum
		*out = make([]MinimumParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeliveryEstimateParameters.
func (in *DeliveryEstimateParameters) DeepCopy() *DeliveryEstimateParameters {
	if in == nil {
		return nil
	}
	out := new(DeliveryEstimateParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FixedAmountInitParameters) DeepCopyInto(out *FixedAmountInitParameters) {
	*out = *in
	if in.Amount != nil {
		in, out := &in.Amount, &out.Amount
		*out = new(float64)
		**out = **in
	}
	if in.Currency != nil {
		in, out := &in.Currency, &out.Currency
		*out = new(string)
		**out = **in
	}
	if in.CurrencyOption != nil {
		in, out := &in.CurrencyOption, &out.CurrencyOption
		*out = make([]CurrencyOptionInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FixedAmountInitParameters.
func (in *FixedAmountInitParameters) DeepCopy() *FixedAmountInitParameters {
	if in == nil {
		return nil
	}
	out := new(FixedAmountInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FixedAmountObservation) DeepCopyInto(out *FixedAmountObservation) {
	*out = *in
	if in.Amount != nil {
		in, out := &in.Amount, &out.Amount
		*out = new(float64)
		**out = **in
	}
	if in.Currency != nil {
		in, out := &in.Currency, &out.Currency
		*out = new(string)
		**out = **in
	}
	if in.CurrencyOption != nil {
		in, out := &in.CurrencyOption, &out.CurrencyOption
		*out = make([]CurrencyOptionObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FixedAmountObservation.
func (in *FixedAmountObservation) DeepCopy() *FixedAmountObservation {
	if in == nil {
		return nil
	}
	out := new(FixedAmountObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FixedAmountParameters) DeepCopyInto(out *FixedAmountParameters) {
	*out = *in
	if in.Amount != nil {
		in, out := &in.Amount, &out.Amount
		*out = new(float64)
		**out = **in
	}
	if in.Currency != nil {
		in, out := &in.Currency, &out.Currency
		*out = new(string)
		**out = **in
	}
	if in.CurrencyOption != nil {
		in, out := &in.CurrencyOption, &out.CurrencyOption
		*out = make([]CurrencyOptionParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FixedAmountParameters.
func (in *FixedAmountParameters) DeepCopy() *FixedAmountParameters {
	if in == nil {
		return nil
	}
	out := new(FixedAmountParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaximumInitParameters) DeepCopyInto(out *MaximumInitParameters) {
	*out = *in
	if in.Unit != nil {
		in, out := &in.Unit, &out.Unit
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaximumInitParameters.
func (in *MaximumInitParameters) DeepCopy() *MaximumInitParameters {
	if in == nil {
		return nil
	}
	out := new(MaximumInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaximumObservation) DeepCopyInto(out *MaximumObservation) {
	*out = *in
	if in.Unit != nil {
		in, out := &in.Unit, &out.Unit
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaximumObservation.
func (in *MaximumObservation) DeepCopy() *MaximumObservation {
	if in == nil {
		return nil
	}
	out := new(MaximumObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MaximumParameters) DeepCopyInto(out *MaximumParameters) {
	*out = *in
	if in.Unit != nil {
		in, out := &in.Unit, &out.Unit
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MaximumParameters.
func (in *MaximumParameters) DeepCopy() *MaximumParameters {
	if in == nil {
		return nil
	}
	out := new(MaximumParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinimumInitParameters) DeepCopyInto(out *MinimumInitParameters) {
	*out = *in
	if in.Unit != nil {
		in, out := &in.Unit, &out.Unit
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinimumInitParameters.
func (in *MinimumInitParameters) DeepCopy() *MinimumInitParameters {
	if in == nil {
		return nil
	}
	out := new(MinimumInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinimumObservation) DeepCopyInto(out *MinimumObservation) {
	*out = *in
	if in.Unit != nil {
		in, out := &in.Unit, &out.Unit
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinimumObservation.
func (in *MinimumObservation) DeepCopy() *MinimumObservation {
	if in == nil {
		return nil
	}
	out := new(MinimumObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinimumParameters) DeepCopyInto(out *MinimumParameters) {
	*out = *in
	if in.Unit != nil {
		in, out := &in.Unit, &out.Unit
		*out = new(string)
		**out = **in
	}
	if in.Value != nil {
		in, out := &in.Value, &out.Value
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinimumParameters.
func (in *MinimumParameters) DeepCopy() *MinimumParameters {
	if in == nil {
		return nil
	}
	out := new(MinimumParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShippingRate) DeepCopyInto(out *ShippingRate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShippingRate.
func (in *ShippingRate) DeepCopy() *ShippingRate {
	if in == nil {
		return nil
	}
	out := new(ShippingRate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShippingRate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShippingRateInitParameters) DeepCopyInto(out *ShippingRateInitParameters) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.DeliveryEstimate != nil {
		in, out := &in.DeliveryEstimate, &out.DeliveryEstimate
		*out = make([]DeliveryEstimateInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.FixedAmount != nil {
		in, out := &in.FixedAmount, &out.FixedAmount
		*out = make([]FixedAmountInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.TaxBehavior != nil {
		in, out := &in.TaxBehavior, &out.TaxBehavior
		*out = new(string)
		**out = **in
	}
	if in.TaxCode != nil {
		in, out := &in.TaxCode, &out.TaxCode
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShippingRateInitParameters.
func (in *ShippingRateInitParameters) DeepCopy() *ShippingRateInitParameters {
	if in == nil {
		return nil
	}
	out := new(ShippingRateInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShippingRateList) DeepCopyInto(out *ShippingRateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ShippingRate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShippingRateList.
func (in *ShippingRateList) DeepCopy() *ShippingRateList {
	if in == nil {
		return nil
	}
	out := new(ShippingRateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ShippingRateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShippingRateObservation) DeepCopyInto(out *ShippingRateObservation) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.DeliveryEstimate != nil {
		in, out := &in.DeliveryEstimate, &out.DeliveryEstimate
		*out = make([]DeliveryEstimateObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.FixedAmount != nil {
		in, out := &in.FixedAmount, &out.FixedAmount
		*out = make([]FixedAmountObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Livemode != nil {
		in, out := &in.Livemode, &out.Livemode
		*out = new(bool)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.TaxBehavior != nil {
		in, out := &in.TaxBehavior, &out.TaxBehavior
		*out = new(string)
		**out = **in
	}
	if in.TaxCode != nil {
		in, out := &in.TaxCode, &out.TaxCode
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShippingRateObservation.
func (in *ShippingRateObservation) DeepCopy() *ShippingRateObservation {
	if in == nil {
		return nil
	}
	out := new(ShippingRateObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShippingRateParameters) DeepCopyInto(out *ShippingRateParameters) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.DeliveryEstimate != nil {
		in, out := &in.DeliveryEstimate, &out.DeliveryEstimate
		*out = make([]DeliveryEstimateParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.FixedAmount != nil {
		in, out := &in.FixedAmount, &out.FixedAmount
		*out = make([]FixedAmountParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.TaxBehavior != nil {
		in, out := &in.TaxBehavior, &out.TaxBehavior
		*out = new(string)
		**out = **in
	}
	if in.TaxCode != nil {
		in, out := &in.TaxCode, &out.TaxCode
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShippingRateParameters.
func (in *ShippingRateParameters) DeepCopy() *ShippingRateParameters {
	if in == nil {
		return nil
	}
	out := new(ShippingRateParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShippingRateSpec) DeepCopyInto(out *ShippingRateSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShippingRateSpec.
func (in *ShippingRateSpec) DeepCopy() *ShippingRateSpec {
	if in == nil {
		return nil
	}
	out := new(ShippingRateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShippingRateStatus) DeepCopyInto(out *ShippingRateStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShippingRateStatus.
func (in *ShippingRateStatus) DeepCopy() *ShippingRateStatus {
	if in == nil {
		return nil
	}
	out := new(ShippingRateStatus)
	in.DeepCopyInto(out)
	return out
}
