// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type CurrencyOptionInitParameters struct {

	// Int. A non-negative integer in cents representing how much to charge.
	// A non-negative integer in cents representing how much to charge.
	Amount *float64 `json:"amount,omitempty" tf:"amount,omitempty"`

	// String. Three-letter ISO currency code, in lowercase - supported currencies.
	// Three-letter ISO currency code, in lowercase. Must be a supported currency.
	Currency *string `json:"currency,omitempty" tf:"currency,omitempty"`

	// String. Specifies whether the price is considered inclusive of taxes or exclusive of
	// taxes. One of inclusive, exclusive, or unspecified. Once specified it cannot be changed, default is unspecified.
	// Specifies whether the rate is considered inclusive of taxes or exclusive of taxes. One of inclusive, exclusive, or unspecified.
	TaxBehavior *string `json:"taxBehavior,omitempty" tf:"tax_behavior,omitempty"`
}

type CurrencyOptionObservation struct {

	// Int. A non-negative integer in cents representing how much to charge.
	// A non-negative integer in cents representing how much to charge.
	Amount *float64 `json:"amount,omitempty" tf:"amount,omitempty"`

	// String. Three-letter ISO currency code, in lowercase - supported currencies.
	// Three-letter ISO currency code, in lowercase. Must be a supported currency.
	Currency *string `json:"currency,omitempty" tf:"currency,omitempty"`

	// String. Specifies whether the price is considered inclusive of taxes or exclusive of
	// taxes. One of inclusive, exclusive, or unspecified. Once specified it cannot be changed, default is unspecified.
	// Specifies whether the rate is considered inclusive of taxes or exclusive of taxes. One of inclusive, exclusive, or unspecified.
	TaxBehavior *string `json:"taxBehavior,omitempty" tf:"tax_behavior,omitempty"`
}

type CurrencyOptionParameters struct {

	// Int. A non-negative integer in cents representing how much to charge.
	// A non-negative integer in cents representing how much to charge.
	// +kubebuilder:validation:Optional
	Amount *float64 `json:"amount" tf:"amount,omitempty"`

	// String. Three-letter ISO currency code, in lowercase - supported currencies.
	// Three-letter ISO currency code, in lowercase. Must be a supported currency.
	// +kubebuilder:validation:Optional
	Currency *string `json:"currency" tf:"currency,omitempty"`

	// String. Specifies whether the price is considered inclusive of taxes or exclusive of
	// taxes. One of inclusive, exclusive, or unspecified. Once specified it cannot be changed, default is unspecified.
	// Specifies whether the rate is considered inclusive of taxes or exclusive of taxes. One of inclusive, exclusive, or unspecified.
	// +kubebuilder:validation:Optional
	TaxBehavior *string `json:"taxBehavior,omitempty" tf:"tax_behavior,omitempty"`
}

type DeliveryEstimateInitParameters struct {

	// List(Resource. The upper bound of the estimated range.
	// Please see Delivery Estimate Definition.
	Maximum []MaximumInitParameters `json:"maximum,omitempty" tf:"maximum,omitempty"`

	// List(Resource). The lower bound of the estimated range.
	// Please see Delivery Estimate Definition.
	Minimum []MinimumInitParameters `json:"minimum,omitempty" tf:"minimum,omitempty"`
}

type DeliveryEstimateObservation struct {

	// List(Resource. The upper bound of the estimated range.
	// Please see Delivery Estimate Definition.
	Maximum []MaximumObservation `json:"maximum,omitempty" tf:"maximum,omitempty"`

	// List(Resource). The lower bound of the estimated range.
	// Please see Delivery Estimate Definition.
	Minimum []MinimumObservation `json:"minimum,omitempty" tf:"minimum,omitempty"`
}

type DeliveryEstimateParameters struct {

	// List(Resource. The upper bound of the estimated range.
	// Please see Delivery Estimate Definition.
	// +kubebuilder:validation:Optional
	Maximum []MaximumParameters `json:"maximum,omitempty" tf:"maximum,omitempty"`

	// List(Resource). The lower bound of the estimated range.
	// Please see Delivery Estimate Definition.
	// +kubebuilder:validation:Optional
	Minimum []MinimumParameters `json:"minimum,omitempty" tf:"minimum,omitempty"`
}

type FixedAmountInitParameters struct {

	// Int. A non-negative integer in cents representing how much to charge.
	// A non-negative integer in cents representing how much to charge.
	Amount *float64 `json:"amount,omitempty" tf:"amount,omitempty"`

	// String. Three-letter ISO currency code, in lowercase - supported currencies.
	// Three-letter ISO currency code, in lowercase. Must be a supported currency.
	Currency *string `json:"currency,omitempty" tf:"currency,omitempty"`

	// List(Resource). Please see argument details Currency Option
	// Shipping rates defined in each available currency option. Each key must be a three-letter ISO currency code and a supported currency. For example, to get your shipping rate in eur, fetch the value of the eur key in currency_options. This field is not included by default. To include it in the response, expand the currency_options field.
	CurrencyOption []CurrencyOptionInitParameters `json:"currencyOption,omitempty" tf:"currency_option,omitempty"`
}

type FixedAmountObservation struct {

	// Int. A non-negative integer in cents representing how much to charge.
	// A non-negative integer in cents representing how much to charge.
	Amount *float64 `json:"amount,omitempty" tf:"amount,omitempty"`

	// String. Three-letter ISO currency code, in lowercase - supported currencies.
	// Three-letter ISO currency code, in lowercase. Must be a supported currency.
	Currency *string `json:"currency,omitempty" tf:"currency,omitempty"`

	// List(Resource). Please see argument details Currency Option
	// Shipping rates defined in each available currency option. Each key must be a three-letter ISO currency code and a supported currency. For example, to get your shipping rate in eur, fetch the value of the eur key in currency_options. This field is not included by default. To include it in the response, expand the currency_options field.
	CurrencyOption []CurrencyOptionObservation `json:"currencyOption,omitempty" tf:"currency_option,omitempty"`
}

type FixedAmountParameters struct {

	// Int. A non-negative integer in cents representing how much to charge.
	// A non-negative integer in cents representing how much to charge.
	// +kubebuilder:validation:Optional
	Amount *float64 `json:"amount" tf:"amount,omitempty"`

	// String. Three-letter ISO currency code, in lowercase - supported currencies.
	// Three-letter ISO currency code, in lowercase. Must be a supported currency.
	// +kubebuilder:validation:Optional
	Currency *string `json:"currency" tf:"currency,omitempty"`

	// List(Resource). Please see argument details Currency Option
	// Shipping rates defined in each available currency option. Each key must be a three-letter ISO currency code and a supported currency. For example, to get your shipping rate in eur, fetch the value of the eur key in currency_options. This field is not included by default. To include it in the response, expand the currency_options field.
	// +kubebuilder:validation:Optional
	CurrencyOption []CurrencyOptionParameters `json:"currencyOption,omitempty" tf:"currency_option,omitempty"`
}

type MaximumInitParameters struct {

	// String. A unit of time. Possible values hour, day, business_day, week and month.
	// The upper bound of the estimated range. If empty, represents no lower bound.
	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`

	// Int. Must be greater than 0.
	// Must be greater than 0.
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type MaximumObservation struct {

	// String. A unit of time. Possible values hour, day, business_day, week and month.
	// The upper bound of the estimated range. If empty, represents no lower bound.
	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`

	// Int. Must be greater than 0.
	// Must be greater than 0.
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type MaximumParameters struct {

	// String. A unit of time. Possible values hour, day, business_day, week and month.
	// The upper bound of the estimated range. If empty, represents no lower bound.
	// +kubebuilder:validation:Optional
	Unit *string `json:"unit" tf:"unit,omitempty"`

	// Int. Must be greater than 0.
	// Must be greater than 0.
	// +kubebuilder:validation:Optional
	Value *float64 `json:"value" tf:"value,omitempty"`
}

type MinimumInitParameters struct {

	// String. A unit of time. Possible values hour, day, business_day, week and month.
	// The lower bound of the estimated range. If empty, represents no lower bound.
	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`

	// Int. Must be greater than 0.
	// Must be greater than 0.
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type MinimumObservation struct {

	// String. A unit of time. Possible values hour, day, business_day, week and month.
	// The lower bound of the estimated range. If empty, represents no lower bound.
	Unit *string `json:"unit,omitempty" tf:"unit,omitempty"`

	// Int. Must be greater than 0.
	// Must be greater than 0.
	Value *float64 `json:"value,omitempty" tf:"value,omitempty"`
}

type MinimumParameters struct {

	// String. A unit of time. Possible values hour, day, business_day, week and month.
	// The lower bound of the estimated range. If empty, represents no lower bound.
	// +kubebuilder:validation:Optional
	Unit *string `json:"unit" tf:"unit,omitempty"`

	// Int. Must be greater than 0.
	// Must be greater than 0.
	// +kubebuilder:validation:Optional
	Value *float64 `json:"value" tf:"value,omitempty"`
}

type ShippingRateInitParameters struct {

	// Bool. Whether the shipping rate is active (can't be used when creating). Defaults to true.
	// Whether the shipping rate can be used for new purchases. Defaults to true.
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// List(Resource). The estimated range for how long shipping will take,
	// meant to be displayable to the customer. This will appear on CheckoutSessions.
	// For details please see Delivery Estimate.
	DeliveryEstimate []DeliveryEstimateInitParameters `json:"deliveryEstimate,omitempty" tf:"delivery_estimate,omitempty"`

	// String. The name of the shipping rate, meant to be displayable to the customer.
	// This will appear on CheckoutSessions.
	// The name of the shipping rate, meant to be displayable to the customer. This will appear on CheckoutSessions.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// List(Resource). Describes a fixed amount to charge for shipping.
	// Must be present if type is fixed_amount. For details of individual arguments see Fixed Amount.
	// Describes a fixed amount to charge for shipping. Must be present for now.
	FixedAmount []FixedAmountInitParameters `json:"fixedAmount,omitempty" tf:"fixed_amount,omitempty"`

	// Map(String). Set of key-value pairs that you can attach to an object. This can be useful for
	// storing additional information about the object in a structured format.
	// Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// String. Specifies whether the price is considered inclusive of taxes or exclusive of
	// taxes. One of inclusive, exclusive, or unspecified. Once specified it cannot be changed, default is unspecified.
	// Specifies whether the rate is considered inclusive of taxes or exclusive of taxes. One of inclusive, exclusive, or unspecified.
	TaxBehavior *string `json:"taxBehavior,omitempty" tf:"tax_behavior,omitempty"`

	// String. A tax code ID. The Shipping tax code is txcd_92010001.
	// A tax code ID. The Shipping tax code is txcd_92010001.
	TaxCode *string `json:"taxCode,omitempty" tf:"tax_code,omitempty"`

	// String. The type of calculation to use on the shipping rate. Can only be fixed_amount for now.
	// The type of calculation to use on the shipping rate. Can only be fixed_amount for now
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ShippingRateObservation struct {

	// Bool. Whether the shipping rate is active (can't be used when creating). Defaults to true.
	// Whether the shipping rate can be used for new purchases. Defaults to true.
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// List(Resource). The estimated range for how long shipping will take,
	// meant to be displayable to the customer. This will appear on CheckoutSessions.
	// For details please see Delivery Estimate.
	DeliveryEstimate []DeliveryEstimateObservation `json:"deliveryEstimate,omitempty" tf:"delivery_estimate,omitempty"`

	// String. The name of the shipping rate, meant to be displayable to the customer.
	// This will appear on CheckoutSessions.
	// The name of the shipping rate, meant to be displayable to the customer. This will appear on CheckoutSessions.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// List(Resource). Describes a fixed amount to charge for shipping.
	// Must be present if type is fixed_amount. For details of individual arguments see Fixed Amount.
	// Describes a fixed amount to charge for shipping. Must be present for now.
	FixedAmount []FixedAmountObservation `json:"fixedAmount,omitempty" tf:"fixed_amount,omitempty"`

	// String. The unique identifier for the object.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Bool. Has the value true if the object exists in live mode or the value false if the object exists in test mode.
	// Has the value true if the object exists in live mode or the value false if the object exists in test mode.
	Livemode *bool `json:"livemode,omitempty" tf:"livemode,omitempty"`

	// Map(String). Set of key-value pairs that you can attach to an object. This can be useful for
	// storing additional information about the object in a structured format.
	// Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// String. Specifies whether the price is considered inclusive of taxes or exclusive of
	// taxes. One of inclusive, exclusive, or unspecified. Once specified it cannot be changed, default is unspecified.
	// Specifies whether the rate is considered inclusive of taxes or exclusive of taxes. One of inclusive, exclusive, or unspecified.
	TaxBehavior *string `json:"taxBehavior,omitempty" tf:"tax_behavior,omitempty"`

	// String. A tax code ID. The Shipping tax code is txcd_92010001.
	// A tax code ID. The Shipping tax code is txcd_92010001.
	TaxCode *string `json:"taxCode,omitempty" tf:"tax_code,omitempty"`

	// String. The type of calculation to use on the shipping rate. Can only be fixed_amount for now.
	// The type of calculation to use on the shipping rate. Can only be fixed_amount for now
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ShippingRateParameters struct {

	// Bool. Whether the shipping rate is active (can't be used when creating). Defaults to true.
	// Whether the shipping rate can be used for new purchases. Defaults to true.
	// +kubebuilder:validation:Optional
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// List(Resource). The estimated range for how long shipping will take,
	// meant to be displayable to the customer. This will appear on CheckoutSessions.
	// For details please see Delivery Estimate.
	// +kubebuilder:validation:Optional
	DeliveryEstimate []DeliveryEstimateParameters `json:"deliveryEstimate,omitempty" tf:"delivery_estimate,omitempty"`

	// String. The name of the shipping rate, meant to be displayable to the customer.
	// This will appear on CheckoutSessions.
	// The name of the shipping rate, meant to be displayable to the customer. This will appear on CheckoutSessions.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// List(Resource). Describes a fixed amount to charge for shipping.
	// Must be present if type is fixed_amount. For details of individual arguments see Fixed Amount.
	// Describes a fixed amount to charge for shipping. Must be present for now.
	// +kubebuilder:validation:Optional
	FixedAmount []FixedAmountParameters `json:"fixedAmount,omitempty" tf:"fixed_amount,omitempty"`

	// Map(String). Set of key-value pairs that you can attach to an object. This can be useful for
	// storing additional information about the object in a structured format.
	// Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// String. Specifies whether the price is considered inclusive of taxes or exclusive of
	// taxes. One of inclusive, exclusive, or unspecified. Once specified it cannot be changed, default is unspecified.
	// Specifies whether the rate is considered inclusive of taxes or exclusive of taxes. One of inclusive, exclusive, or unspecified.
	// +kubebuilder:validation:Optional
	TaxBehavior *string `json:"taxBehavior,omitempty" tf:"tax_behavior,omitempty"`

	// String. A tax code ID. The Shipping tax code is txcd_92010001.
	// A tax code ID. The Shipping tax code is txcd_92010001.
	// +kubebuilder:validation:Optional
	TaxCode *string `json:"taxCode,omitempty" tf:"tax_code,omitempty"`

	// String. The type of calculation to use on the shipping rate. Can only be fixed_amount for now.
	// The type of calculation to use on the shipping rate. Can only be fixed_amount for now
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// ShippingRateSpec defines the desired state of ShippingRate
type ShippingRateSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ShippingRateParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ShippingRateInitParameters `json:"initProvider,omitempty"`
}

// ShippingRateStatus defines the observed state of ShippingRate.
type ShippingRateStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ShippingRateObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ShippingRate is the Schema for the ShippingRates API. The Stripe Shipping Rate can be created, modified and configured by this resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,stripe}
type ShippingRate struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.fixedAmount) || (has(self.initProvider) && has(self.initProvider.fixedAmount))",message="spec.forProvider.fixedAmount is a required parameter"
	Spec   ShippingRateSpec   `json:"spec"`
	Status ShippingRateStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ShippingRateList contains a list of ShippingRates
type ShippingRateList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ShippingRate `json:"items"`
}

// Repository type metadata.
var (
	ShippingRate_Kind             = "ShippingRate"
	ShippingRate_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ShippingRate_Kind}.String()
	ShippingRate_KindAPIVersion   = ShippingRate_Kind + "." + CRDGroupVersion.String()
	ShippingRate_GroupVersionKind = CRDGroupVersion.WithKind(ShippingRate_Kind)
)

func init() {
	SchemeBuilder.Register(&ShippingRate{}, &ShippingRateList{})
}
