// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ProductFeatureInitParameters struct {

	// The ID of the Entitlements Feature the product will be attached to
	EntitlementsFeature *string `json:"entitlementsFeature,omitempty" tf:"entitlements_feature,omitempty"`

	// The ID of the product that this Entitlements Feature will be attached to.
	Product *string `json:"product,omitempty" tf:"product,omitempty"`
}

type ProductFeatureObservation struct {

	// The ID of the Entitlements Feature the product will be attached to
	EntitlementsFeature *string `json:"entitlementsFeature,omitempty" tf:"entitlements_feature,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Has the value true if the object exists in live mode or the value false if the object exists in test mode
	Livemode *bool `json:"livemode,omitempty" tf:"livemode,omitempty"`

	// String representing the object’s type. Objects of the same type share the same value.
	Object *string `json:"object,omitempty" tf:"object,omitempty"`

	// The ID of the product that this Entitlements Feature will be attached to.
	Product *string `json:"product,omitempty" tf:"product,omitempty"`
}

type ProductFeatureParameters struct {

	// The ID of the Entitlements Feature the product will be attached to
	// +kubebuilder:validation:Optional
	EntitlementsFeature *string `json:"entitlementsFeature,omitempty" tf:"entitlements_feature,omitempty"`

	// The ID of the product that this Entitlements Feature will be attached to.
	// +kubebuilder:validation:Optional
	Product *string `json:"product,omitempty" tf:"product,omitempty"`
}

// ProductFeatureSpec defines the desired state of ProductFeature
type ProductFeatureSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ProductFeatureParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ProductFeatureInitParameters `json:"initProvider,omitempty"`
}

// ProductFeatureStatus defines the observed state of ProductFeature.
type ProductFeatureStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ProductFeatureObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ProductFeature is the Schema for the ProductFeatures API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,stripe}
type ProductFeature struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.entitlementsFeature) || (has(self.initProvider) && has(self.initProvider.entitlementsFeature))",message="spec.forProvider.entitlementsFeature is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.product) || (has(self.initProvider) && has(self.initProvider.product))",message="spec.forProvider.product is a required parameter"
	Spec   ProductFeatureSpec   `json:"spec"`
	Status ProductFeatureStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProductFeatureList contains a list of ProductFeatures
type ProductFeatureList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ProductFeature `json:"items"`
}

// Repository type metadata.
var (
	ProductFeature_Kind             = "ProductFeature"
	ProductFeature_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ProductFeature_Kind}.String()
	ProductFeature_KindAPIVersion   = ProductFeature_Kind + "." + CRDGroupVersion.String()
	ProductFeature_GroupVersionKind = CRDGroupVersion.WithKind(ProductFeature_Kind)
)

func init() {
	SchemeBuilder.Register(&ProductFeature{}, &ProductFeatureList{})
}
