//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BusinessProfileInitParameters) DeepCopyInto(out *BusinessProfileInitParameters) {
	*out = *in
	if in.Headline != nil {
		in, out := &in.Headline, &out.Headline
		*out = new(string)
		**out = **in
	}
	if in.PrivacyPolicyURL != nil {
		in, out := &in.PrivacyPolicyURL, &out.PrivacyPolicyURL
		*out = new(string)
		**out = **in
	}
	if in.TermsOfServiceURL != nil {
		in, out := &in.TermsOfServiceURL, &out.TermsOfServiceURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BusinessProfileInitParameters.
func (in *BusinessProfileInitParameters) DeepCopy() *BusinessProfileInitParameters {
	if in == nil {
		return nil
	}
	out := new(BusinessProfileInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BusinessProfileObservation) DeepCopyInto(out *BusinessProfileObservation) {
	*out = *in
	if in.Headline != nil {
		in, out := &in.Headline, &out.Headline
		*out = new(string)
		**out = **in
	}
	if in.PrivacyPolicyURL != nil {
		in, out := &in.PrivacyPolicyURL, &out.PrivacyPolicyURL
		*out = new(string)
		**out = **in
	}
	if in.TermsOfServiceURL != nil {
		in, out := &in.TermsOfServiceURL, &out.TermsOfServiceURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BusinessProfileObservation.
func (in *BusinessProfileObservation) DeepCopy() *BusinessProfileObservation {
	if in == nil {
		return nil
	}
	out := new(BusinessProfileObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BusinessProfileParameters) DeepCopyInto(out *BusinessProfileParameters) {
	*out = *in
	if in.Headline != nil {
		in, out := &in.Headline, &out.Headline
		*out = new(string)
		**out = **in
	}
	if in.PrivacyPolicyURL != nil {
		in, out := &in.PrivacyPolicyURL, &out.PrivacyPolicyURL
		*out = new(string)
		**out = **in
	}
	if in.TermsOfServiceURL != nil {
		in, out := &in.TermsOfServiceURL, &out.TermsOfServiceURL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BusinessProfileParameters.
func (in *BusinessProfileParameters) DeepCopy() *BusinessProfileParameters {
	if in == nil {
		return nil
	}
	out := new(BusinessProfileParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CancellationReasonInitParameters) DeepCopyInto(out *CancellationReasonInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CancellationReasonInitParameters.
func (in *CancellationReasonInitParameters) DeepCopy() *CancellationReasonInitParameters {
	if in == nil {
		return nil
	}
	out := new(CancellationReasonInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CancellationReasonObservation) DeepCopyInto(out *CancellationReasonObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CancellationReasonObservation.
func (in *CancellationReasonObservation) DeepCopy() *CancellationReasonObservation {
	if in == nil {
		return nil
	}
	out := new(CancellationReasonObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CancellationReasonParameters) DeepCopyInto(out *CancellationReasonParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CancellationReasonParameters.
func (in *CancellationReasonParameters) DeepCopy() *CancellationReasonParameters {
	if in == nil {
		return nil
	}
	out := new(CancellationReasonParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Configuration) DeepCopyInto(out *Configuration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Configuration.
func (in *Configuration) DeepCopy() *Configuration {
	if in == nil {
		return nil
	}
	out := new(Configuration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Configuration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationInitParameters) DeepCopyInto(out *ConfigurationInitParameters) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.BusinessProfile != nil {
		in, out := &in.BusinessProfile, &out.BusinessProfile
		*out = make([]BusinessProfileInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DefaultReturnURL != nil {
		in, out := &in.DefaultReturnURL, &out.DefaultReturnURL
		*out = new(string)
		**out = **in
	}
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = make([]FeaturesInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LoginPage != nil {
		in, out := &in.LoginPage, &out.LoginPage
		*out = make([]LoginPageInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationInitParameters.
func (in *ConfigurationInitParameters) DeepCopy() *ConfigurationInitParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigurationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationList) DeepCopyInto(out *ConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Configuration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationList.
func (in *ConfigurationList) DeepCopy() *ConfigurationList {
	if in == nil {
		return nil
	}
	out := new(ConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationObservation) DeepCopyInto(out *ConfigurationObservation) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.BusinessProfile != nil {
		in, out := &in.BusinessProfile, &out.BusinessProfile
		*out = make([]BusinessProfileObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DefaultReturnURL != nil {
		in, out := &in.DefaultReturnURL, &out.DefaultReturnURL
		*out = new(string)
		**out = **in
	}
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = make([]FeaturesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IsDefault != nil {
		in, out := &in.IsDefault, &out.IsDefault
		*out = new(bool)
		**out = **in
	}
	if in.LoginPage != nil {
		in, out := &in.LoginPage, &out.LoginPage
		*out = make([]LoginPageObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationObservation.
func (in *ConfigurationObservation) DeepCopy() *ConfigurationObservation {
	if in == nil {
		return nil
	}
	out := new(ConfigurationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationParameters) DeepCopyInto(out *ConfigurationParameters) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.BusinessProfile != nil {
		in, out := &in.BusinessProfile, &out.BusinessProfile
		*out = make([]BusinessProfileParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DefaultReturnURL != nil {
		in, out := &in.DefaultReturnURL, &out.DefaultReturnURL
		*out = new(string)
		**out = **in
	}
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = make([]FeaturesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LoginPage != nil {
		in, out := &in.LoginPage, &out.LoginPage
		*out = make([]LoginPageParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationParameters.
func (in *ConfigurationParameters) DeepCopy() *ConfigurationParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigurationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationSpec) DeepCopyInto(out *ConfigurationSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationSpec.
func (in *ConfigurationSpec) DeepCopy() *ConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationStatus) DeepCopyInto(out *ConfigurationStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationStatus.
func (in *ConfigurationStatus) DeepCopy() *ConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(ConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomerUpdateInitParameters) DeepCopyInto(out *CustomerUpdateInitParameters) {
	*out = *in
	if in.AllowedUpdates != nil {
		in, out := &in.AllowedUpdates, &out.AllowedUpdates
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomerUpdateInitParameters.
func (in *CustomerUpdateInitParameters) DeepCopy() *CustomerUpdateInitParameters {
	if in == nil {
		return nil
	}
	out := new(CustomerUpdateInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomerUpdateObservation) DeepCopyInto(out *CustomerUpdateObservation) {
	*out = *in
	if in.AllowedUpdates != nil {
		in, out := &in.AllowedUpdates, &out.AllowedUpdates
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomerUpdateObservation.
func (in *CustomerUpdateObservation) DeepCopy() *CustomerUpdateObservation {
	if in == nil {
		return nil
	}
	out := new(CustomerUpdateObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomerUpdateParameters) DeepCopyInto(out *CustomerUpdateParameters) {
	*out = *in
	if in.AllowedUpdates != nil {
		in, out := &in.AllowedUpdates, &out.AllowedUpdates
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomerUpdateParameters.
func (in *CustomerUpdateParameters) DeepCopy() *CustomerUpdateParameters {
	if in == nil {
		return nil
	}
	out := new(CustomerUpdateParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeaturesInitParameters) DeepCopyInto(out *FeaturesInitParameters) {
	*out = *in
	if in.CustomerUpdate != nil {
		in, out := &in.CustomerUpdate, &out.CustomerUpdate
		*out = make([]CustomerUpdateInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InvoiceHistory != nil {
		in, out := &in.InvoiceHistory, &out.InvoiceHistory
		*out = make([]InvoiceHistoryInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PaymentMethodUpdate != nil {
		in, out := &in.PaymentMethodUpdate, &out.PaymentMethodUpdate
		*out = make([]PaymentMethodUpdateInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SubscriptionCancel != nil {
		in, out := &in.SubscriptionCancel, &out.SubscriptionCancel
		*out = make([]SubscriptionCancelInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SubscriptionUpdate != nil {
		in, out := &in.SubscriptionUpdate, &out.SubscriptionUpdate
		*out = make([]SubscriptionUpdateInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeaturesInitParameters.
func (in *FeaturesInitParameters) DeepCopy() *FeaturesInitParameters {
	if in == nil {
		return nil
	}
	out := new(FeaturesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeaturesObservation) DeepCopyInto(out *FeaturesObservation) {
	*out = *in
	if in.CustomerUpdate != nil {
		in, out := &in.CustomerUpdate, &out.CustomerUpdate
		*out = make([]CustomerUpdateObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InvoiceHistory != nil {
		in, out := &in.InvoiceHistory, &out.InvoiceHistory
		*out = make([]InvoiceHistoryObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PaymentMethodUpdate != nil {
		in, out := &in.PaymentMethodUpdate, &out.PaymentMethodUpdate
		*out = make([]PaymentMethodUpdateObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SubscriptionCancel != nil {
		in, out := &in.SubscriptionCancel, &out.SubscriptionCancel
		*out = make([]SubscriptionCancelObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SubscriptionUpdate != nil {
		in, out := &in.SubscriptionUpdate, &out.SubscriptionUpdate
		*out = make([]SubscriptionUpdateObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeaturesObservation.
func (in *FeaturesObservation) DeepCopy() *FeaturesObservation {
	if in == nil {
		return nil
	}
	out := new(FeaturesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeaturesParameters) DeepCopyInto(out *FeaturesParameters) {
	*out = *in
	if in.CustomerUpdate != nil {
		in, out := &in.CustomerUpdate, &out.CustomerUpdate
		*out = make([]CustomerUpdateParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InvoiceHistory != nil {
		in, out := &in.InvoiceHistory, &out.InvoiceHistory
		*out = make([]InvoiceHistoryParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PaymentMethodUpdate != nil {
		in, out := &in.PaymentMethodUpdate, &out.PaymentMethodUpdate
		*out = make([]PaymentMethodUpdateParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SubscriptionCancel != nil {
		in, out := &in.SubscriptionCancel, &out.SubscriptionCancel
		*out = make([]SubscriptionCancelParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SubscriptionUpdate != nil {
		in, out := &in.SubscriptionUpdate, &out.SubscriptionUpdate
		*out = make([]SubscriptionUpdateParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeaturesParameters.
func (in *FeaturesParameters) DeepCopy() *FeaturesParameters {
	if in == nil {
		return nil
	}
	out := new(FeaturesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoiceHistoryInitParameters) DeepCopyInto(out *InvoiceHistoryInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoiceHistoryInitParameters.
func (in *InvoiceHistoryInitParameters) DeepCopy() *InvoiceHistoryInitParameters {
	if in == nil {
		return nil
	}
	out := new(InvoiceHistoryInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoiceHistoryObservation) DeepCopyInto(out *InvoiceHistoryObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoiceHistoryObservation.
func (in *InvoiceHistoryObservation) DeepCopy() *InvoiceHistoryObservation {
	if in == nil {
		return nil
	}
	out := new(InvoiceHistoryObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InvoiceHistoryParameters) DeepCopyInto(out *InvoiceHistoryParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InvoiceHistoryParameters.
func (in *InvoiceHistoryParameters) DeepCopy() *InvoiceHistoryParameters {
	if in == nil {
		return nil
	}
	out := new(InvoiceHistoryParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoginPageInitParameters) DeepCopyInto(out *LoginPageInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoginPageInitParameters.
func (in *LoginPageInitParameters) DeepCopy() *LoginPageInitParameters {
	if in == nil {
		return nil
	}
	out := new(LoginPageInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoginPageObservation) DeepCopyInto(out *LoginPageObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoginPageObservation.
func (in *LoginPageObservation) DeepCopy() *LoginPageObservation {
	if in == nil {
		return nil
	}
	out := new(LoginPageObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoginPageParameters) DeepCopyInto(out *LoginPageParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoginPageParameters.
func (in *LoginPageParameters) DeepCopy() *LoginPageParameters {
	if in == nil {
		return nil
	}
	out := new(LoginPageParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaymentMethodUpdateInitParameters) DeepCopyInto(out *PaymentMethodUpdateInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaymentMethodUpdateInitParameters.
func (in *PaymentMethodUpdateInitParameters) DeepCopy() *PaymentMethodUpdateInitParameters {
	if in == nil {
		return nil
	}
	out := new(PaymentMethodUpdateInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaymentMethodUpdateObservation) DeepCopyInto(out *PaymentMethodUpdateObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaymentMethodUpdateObservation.
func (in *PaymentMethodUpdateObservation) DeepCopy() *PaymentMethodUpdateObservation {
	if in == nil {
		return nil
	}
	out := new(PaymentMethodUpdateObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PaymentMethodUpdateParameters) DeepCopyInto(out *PaymentMethodUpdateParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PaymentMethodUpdateParameters.
func (in *PaymentMethodUpdateParameters) DeepCopy() *PaymentMethodUpdateParameters {
	if in == nil {
		return nil
	}
	out := new(PaymentMethodUpdateParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProductsInitParameters) DeepCopyInto(out *ProductsInitParameters) {
	*out = *in
	if in.Prices != nil {
		in, out := &in.Prices, &out.Prices
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Product != nil {
		in, out := &in.Product, &out.Product
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProductsInitParameters.
func (in *ProductsInitParameters) DeepCopy() *ProductsInitParameters {
	if in == nil {
		return nil
	}
	out := new(ProductsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProductsObservation) DeepCopyInto(out *ProductsObservation) {
	*out = *in
	if in.Prices != nil {
		in, out := &in.Prices, &out.Prices
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Product != nil {
		in, out := &in.Product, &out.Product
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProductsObservation.
func (in *ProductsObservation) DeepCopy() *ProductsObservation {
	if in == nil {
		return nil
	}
	out := new(ProductsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProductsParameters) DeepCopyInto(out *ProductsParameters) {
	*out = *in
	if in.Prices != nil {
		in, out := &in.Prices, &out.Prices
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Product != nil {
		in, out := &in.Product, &out.Product
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProductsParameters.
func (in *ProductsParameters) DeepCopy() *ProductsParameters {
	if in == nil {
		return nil
	}
	out := new(ProductsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionCancelInitParameters) DeepCopyInto(out *SubscriptionCancelInitParameters) {
	*out = *in
	if in.CancellationReason != nil {
		in, out := &in.CancellationReason, &out.CancellationReason
		*out = make([]CancellationReasonInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	if in.ProrationBehavior != nil {
		in, out := &in.ProrationBehavior, &out.ProrationBehavior
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionCancelInitParameters.
func (in *SubscriptionCancelInitParameters) DeepCopy() *SubscriptionCancelInitParameters {
	if in == nil {
		return nil
	}
	out := new(SubscriptionCancelInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionCancelObservation) DeepCopyInto(out *SubscriptionCancelObservation) {
	*out = *in
	if in.CancellationReason != nil {
		in, out := &in.CancellationReason, &out.CancellationReason
		*out = make([]CancellationReasonObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	if in.ProrationBehavior != nil {
		in, out := &in.ProrationBehavior, &out.ProrationBehavior
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionCancelObservation.
func (in *SubscriptionCancelObservation) DeepCopy() *SubscriptionCancelObservation {
	if in == nil {
		return nil
	}
	out := new(SubscriptionCancelObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionCancelParameters) DeepCopyInto(out *SubscriptionCancelParameters) {
	*out = *in
	if in.CancellationReason != nil {
		in, out := &in.CancellationReason, &out.CancellationReason
		*out = make([]CancellationReasonParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	if in.ProrationBehavior != nil {
		in, out := &in.ProrationBehavior, &out.ProrationBehavior
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionCancelParameters.
func (in *SubscriptionCancelParameters) DeepCopy() *SubscriptionCancelParameters {
	if in == nil {
		return nil
	}
	out := new(SubscriptionCancelParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionUpdateInitParameters) DeepCopyInto(out *SubscriptionUpdateInitParameters) {
	*out = *in
	if in.DefaultAllowedUpdates != nil {
		in, out := &in.DefaultAllowedUpdates, &out.DefaultAllowedUpdates
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Products != nil {
		in, out := &in.Products, &out.Products
		*out = make([]ProductsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ProrationBehavior != nil {
		in, out := &in.ProrationBehavior, &out.ProrationBehavior
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionUpdateInitParameters.
func (in *SubscriptionUpdateInitParameters) DeepCopy() *SubscriptionUpdateInitParameters {
	if in == nil {
		return nil
	}
	out := new(SubscriptionUpdateInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionUpdateObservation) DeepCopyInto(out *SubscriptionUpdateObservation) {
	*out = *in
	if in.DefaultAllowedUpdates != nil {
		in, out := &in.DefaultAllowedUpdates, &out.DefaultAllowedUpdates
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Products != nil {
		in, out := &in.Products, &out.Products
		*out = make([]ProductsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ProrationBehavior != nil {
		in, out := &in.ProrationBehavior, &out.ProrationBehavior
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionUpdateObservation.
func (in *SubscriptionUpdateObservation) DeepCopy() *SubscriptionUpdateObservation {
	if in == nil {
		return nil
	}
	out := new(SubscriptionUpdateObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubscriptionUpdateParameters) DeepCopyInto(out *SubscriptionUpdateParameters) {
	*out = *in
	if in.DefaultAllowedUpdates != nil {
		in, out := &in.DefaultAllowedUpdates, &out.DefaultAllowedUpdates
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Products != nil {
		in, out := &in.Products, &out.Products
		*out = make([]ProductsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ProrationBehavior != nil {
		in, out := &in.ProrationBehavior, &out.ProrationBehavior
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubscriptionUpdateParameters.
func (in *SubscriptionUpdateParameters) DeepCopy() *SubscriptionUpdateParameters {
	if in == nil {
		return nil
	}
	out := new(SubscriptionUpdateParameters)
	in.DeepCopyInto(out)
	return out
}
