apiVersion: stripepromotioncode.stripe.m.crossplane.io/v1alpha1
kind: Code
metadata:
  annotations:
    meta.upbound.io/example-id: stripepromotioncode/v1alpha1/code
  labels:
    testing.upbound.io/example-name: code
  name: code
  namespace: crossplane-system
spec:
  forProvider:
    code: FREE
    coupon: ${stripe_coupon.coupon.id}
