// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ProductInitParameters struct {

	// Bool. Whether the product is currently available for purchase. Defaults to true.
	// Whether the product is currently available for purchase. Defaults to true.
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// String. The product’s description, meant to be displayable to the customer. Use this field to optionally store a long form explanation of the product being sold for your own rendering purposes.
	// The product’s description, meant to be displayable to the customer. Use this field to optionally store a long form explanation of the product being sold for your own rendering purposes.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// List(String). A list of up to 8 URLs of images for this product, meant to be displayable to the customer.
	// A list of up to 8 URLs of images for this product, meant to be displayable to the customer.
	Images []*string `json:"images,omitempty" tf:"images,omitempty"`

	// List(String). A list of up to 15 marketing features for this product. These are displayed in pricing tables.
	// A list of up to 15 marketing features for this product. These are displayed in pricing tables.
	MarketingFeatures []*string `json:"marketingFeatures,omitempty" tf:"marketing_features,omitempty"`

	// Map(String). Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
	// Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// String. The product’s name, meant to be displayable to the customer. Whenever this product is sold via a subscription, name will show up on associated invoice line item descriptions.
	// The product’s name, meant to be displayable to the customer. Whenever this product is sold via a subscription, name will show up on associated invoice line item descriptions.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Map(Float). The dimensions of this product for shipping purposes. When used these fields are required: height,length,width and weight; the precision is 2 decimal places.
	// The dimensions of this product for shipping purposes.
	// +mapType=granular
	PackageDimensions map[string]*float64 `json:"packageDimensions,omitempty" tf:"package_dimensions,omitempty"`

	// String. The bespoke unique identifier for the object.
	// Unique identifier for the object.
	ProductID *string `json:"productId,omitempty" tf:"product_id,omitempty"`

	// Bool. Whether this product is shipped (i.e., physical goods).
	// Whether this product is shipped (i.e., physical goods).
	Shippable *bool `json:"shippable,omitempty" tf:"shippable,omitempty"`

	// String. An arbitrary string to be displayed on your customer’s credit card or bank statement. While most banks display this information consistently, some may display it incorrectly or not at all. This may be up to 22 characters. The statement description may not include <, >, \, ", ’ characters, and will appear on your customer’s statement in capital letters. Non-ASCII characters are automatically stripped. It must contain at least one letter.
	// An arbitrary string to be displayed on your customer’s credit card or bank statement. While most banks display this information consistently, some may display it incorrectly or not at all. This may be up to 22 characters. The statement description may not include <, >, \, ", ’ characters, and will appear on your customer’s statement in capital letters. Non-ASCII characters are automatically stripped. It must contain at least one letter.
	StatementDescriptor *string `json:"statementDescriptor,omitempty" tf:"statement_descriptor,omitempty"`

	// String. A tax code ID. Supported values are listed in the TaxCode resource and at https://stripe.com/docs/tax/tax-categories.
	// A tax code ID. Supported values are listed in the TaxCode resource and at https://stripe.com/docs/tax/tax-categories.
	TaxCode *string `json:"taxCode,omitempty" tf:"tax_code,omitempty"`

	// String. A URL of a publicly-accessible webpage for this product.
	// A URL of a publicly-accessible webpage for this product.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// String. A label that represents units of this product in Stripe and on customers’ receipts and invoices. When set, this will be included in associated invoice line item descriptions.
	// A label that represents units of this product in Stripe and on customers’ receipts and invoices. When set, this will be included in associated invoice line item descriptions.
	UnitLabel *string `json:"unitLabel,omitempty" tf:"unit_label,omitempty"`
}

type ProductObservation struct {

	// Bool. Whether the product is currently available for purchase. Defaults to true.
	// Whether the product is currently available for purchase. Defaults to true.
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// String. The product’s description, meant to be displayable to the customer. Use this field to optionally store a long form explanation of the product being sold for your own rendering purposes.
	// The product’s description, meant to be displayable to the customer. Use this field to optionally store a long form explanation of the product being sold for your own rendering purposes.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// String. The unique identifier for the object.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// List(String). A list of up to 8 URLs of images for this product, meant to be displayable to the customer.
	// A list of up to 8 URLs of images for this product, meant to be displayable to the customer.
	Images []*string `json:"images,omitempty" tf:"images,omitempty"`

	// List(String). A list of up to 15 marketing features for this product. These are displayed in pricing tables.
	// A list of up to 15 marketing features for this product. These are displayed in pricing tables.
	MarketingFeatures []*string `json:"marketingFeatures,omitempty" tf:"marketing_features,omitempty"`

	// Map(String). Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
	// Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// String. The product’s name, meant to be displayable to the customer. Whenever this product is sold via a subscription, name will show up on associated invoice line item descriptions.
	// The product’s name, meant to be displayable to the customer. Whenever this product is sold via a subscription, name will show up on associated invoice line item descriptions.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Map(Float). The dimensions of this product for shipping purposes. When used these fields are required: height,length,width and weight; the precision is 2 decimal places.
	// The dimensions of this product for shipping purposes.
	// +mapType=granular
	PackageDimensions map[string]*float64 `json:"packageDimensions,omitempty" tf:"package_dimensions,omitempty"`

	// String. The bespoke unique identifier for the object.
	// Unique identifier for the object.
	ProductID *string `json:"productId,omitempty" tf:"product_id,omitempty"`

	// Bool. Whether this product is shipped (i.e., physical goods).
	// Whether this product is shipped (i.e., physical goods).
	Shippable *bool `json:"shippable,omitempty" tf:"shippable,omitempty"`

	// String. An arbitrary string to be displayed on your customer’s credit card or bank statement. While most banks display this information consistently, some may display it incorrectly or not at all. This may be up to 22 characters. The statement description may not include <, >, \, ", ’ characters, and will appear on your customer’s statement in capital letters. Non-ASCII characters are automatically stripped. It must contain at least one letter.
	// An arbitrary string to be displayed on your customer’s credit card or bank statement. While most banks display this information consistently, some may display it incorrectly or not at all. This may be up to 22 characters. The statement description may not include <, >, \, ", ’ characters, and will appear on your customer’s statement in capital letters. Non-ASCII characters are automatically stripped. It must contain at least one letter.
	StatementDescriptor *string `json:"statementDescriptor,omitempty" tf:"statement_descriptor,omitempty"`

	// String. A tax code ID. Supported values are listed in the TaxCode resource and at https://stripe.com/docs/tax/tax-categories.
	// A tax code ID. Supported values are listed in the TaxCode resource and at https://stripe.com/docs/tax/tax-categories.
	TaxCode *string `json:"taxCode,omitempty" tf:"tax_code,omitempty"`

	// String. A URL of a publicly-accessible webpage for this product.
	// A URL of a publicly-accessible webpage for this product.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// String. A label that represents units of this product in Stripe and on customers’ receipts and invoices. When set, this will be included in associated invoice line item descriptions.
	// A label that represents units of this product in Stripe and on customers’ receipts and invoices. When set, this will be included in associated invoice line item descriptions.
	UnitLabel *string `json:"unitLabel,omitempty" tf:"unit_label,omitempty"`
}

type ProductParameters struct {

	// Bool. Whether the product is currently available for purchase. Defaults to true.
	// Whether the product is currently available for purchase. Defaults to true.
	// +kubebuilder:validation:Optional
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// String. The product’s description, meant to be displayable to the customer. Use this field to optionally store a long form explanation of the product being sold for your own rendering purposes.
	// The product’s description, meant to be displayable to the customer. Use this field to optionally store a long form explanation of the product being sold for your own rendering purposes.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// List(String). A list of up to 8 URLs of images for this product, meant to be displayable to the customer.
	// A list of up to 8 URLs of images for this product, meant to be displayable to the customer.
	// +kubebuilder:validation:Optional
	Images []*string `json:"images,omitempty" tf:"images,omitempty"`

	// List(String). A list of up to 15 marketing features for this product. These are displayed in pricing tables.
	// A list of up to 15 marketing features for this product. These are displayed in pricing tables.
	// +kubebuilder:validation:Optional
	MarketingFeatures []*string `json:"marketingFeatures,omitempty" tf:"marketing_features,omitempty"`

	// Map(String). Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
	// Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// String. The product’s name, meant to be displayable to the customer. Whenever this product is sold via a subscription, name will show up on associated invoice line item descriptions.
	// The product’s name, meant to be displayable to the customer. Whenever this product is sold via a subscription, name will show up on associated invoice line item descriptions.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Map(Float). The dimensions of this product for shipping purposes. When used these fields are required: height,length,width and weight; the precision is 2 decimal places.
	// The dimensions of this product for shipping purposes.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	PackageDimensions map[string]*float64 `json:"packageDimensions,omitempty" tf:"package_dimensions,omitempty"`

	// String. The bespoke unique identifier for the object.
	// Unique identifier for the object.
	// +kubebuilder:validation:Optional
	ProductID *string `json:"productId,omitempty" tf:"product_id,omitempty"`

	// Bool. Whether this product is shipped (i.e., physical goods).
	// Whether this product is shipped (i.e., physical goods).
	// +kubebuilder:validation:Optional
	Shippable *bool `json:"shippable,omitempty" tf:"shippable,omitempty"`

	// String. An arbitrary string to be displayed on your customer’s credit card or bank statement. While most banks display this information consistently, some may display it incorrectly or not at all. This may be up to 22 characters. The statement description may not include <, >, \, ", ’ characters, and will appear on your customer’s statement in capital letters. Non-ASCII characters are automatically stripped. It must contain at least one letter.
	// An arbitrary string to be displayed on your customer’s credit card or bank statement. While most banks display this information consistently, some may display it incorrectly or not at all. This may be up to 22 characters. The statement description may not include <, >, \, ", ’ characters, and will appear on your customer’s statement in capital letters. Non-ASCII characters are automatically stripped. It must contain at least one letter.
	// +kubebuilder:validation:Optional
	StatementDescriptor *string `json:"statementDescriptor,omitempty" tf:"statement_descriptor,omitempty"`

	// String. A tax code ID. Supported values are listed in the TaxCode resource and at https://stripe.com/docs/tax/tax-categories.
	// A tax code ID. Supported values are listed in the TaxCode resource and at https://stripe.com/docs/tax/tax-categories.
	// +kubebuilder:validation:Optional
	TaxCode *string `json:"taxCode,omitempty" tf:"tax_code,omitempty"`

	// String. A URL of a publicly-accessible webpage for this product.
	// A URL of a publicly-accessible webpage for this product.
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// String. A label that represents units of this product in Stripe and on customers’ receipts and invoices. When set, this will be included in associated invoice line item descriptions.
	// A label that represents units of this product in Stripe and on customers’ receipts and invoices. When set, this will be included in associated invoice line item descriptions.
	// +kubebuilder:validation:Optional
	UnitLabel *string `json:"unitLabel,omitempty" tf:"unit_label,omitempty"`
}

// ProductSpec defines the desired state of Product
type ProductSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ProductParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ProductInitParameters `json:"initProvider,omitempty"`
}

// ProductStatus defines the observed state of Product.
type ProductStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ProductObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Product is the Schema for the Products API. The Stripe Product can be created, modified, configured and removed by this resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,stripe}
type Product struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ProductSpec   `json:"spec"`
	Status ProductStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProductList contains a list of Products
type ProductList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Product `json:"items"`
}

// Repository type metadata.
var (
	Product_Kind             = "Product"
	Product_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Product_Kind}.String()
	Product_KindAPIVersion   = Product_Kind + "." + CRDGroupVersion.String()
	Product_GroupVersionKind = CRDGroupVersion.WithKind(Product_Kind)
)

func init() {
	SchemeBuilder.Register(&Product{}, &ProductList{})
}
