//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Code) DeepCopyInto(out *Code) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Code.
func (in *Code) DeepCopy() *Code {
	if in == nil {
		return nil
	}
	out := new(Code)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Code) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeInitParameters) DeepCopyInto(out *CodeInitParameters) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.Code != nil {
		in, out := &in.Code, &out.Code
		*out = new(string)
		**out = **in
	}
	if in.Coupon != nil {
		in, out := &in.Coupon, &out.Coupon
		*out = new(string)
		**out = **in
	}
	if in.Customer != nil {
		in, out := &in.Customer, &out.Customer
		*out = new(string)
		**out = **in
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = new(string)
		**out = **in
	}
	if in.MaxRedemptions != nil {
		in, out := &in.MaxRedemptions, &out.MaxRedemptions
		*out = new(float64)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Restrictions != nil {
		in, out := &in.Restrictions, &out.Restrictions
		*out = make([]RestrictionsInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeInitParameters.
func (in *CodeInitParameters) DeepCopy() *CodeInitParameters {
	if in == nil {
		return nil
	}
	out := new(CodeInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeList) DeepCopyInto(out *CodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Code, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeList.
func (in *CodeList) DeepCopy() *CodeList {
	if in == nil {
		return nil
	}
	out := new(CodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeObservation) DeepCopyInto(out *CodeObservation) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.Code != nil {
		in, out := &in.Code, &out.Code
		*out = new(string)
		**out = **in
	}
	if in.Coupon != nil {
		in, out := &in.Coupon, &out.Coupon
		*out = new(string)
		**out = **in
	}
	if in.Customer != nil {
		in, out := &in.Customer, &out.Customer
		*out = new(string)
		**out = **in
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.MaxRedemptions != nil {
		in, out := &in.MaxRedemptions, &out.MaxRedemptions
		*out = new(float64)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Restrictions != nil {
		in, out := &in.Restrictions, &out.Restrictions
		*out = make([]RestrictionsObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeObservation.
func (in *CodeObservation) DeepCopy() *CodeObservation {
	if in == nil {
		return nil
	}
	out := new(CodeObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeParameters) DeepCopyInto(out *CodeParameters) {
	*out = *in
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = new(bool)
		**out = **in
	}
	if in.Code != nil {
		in, out := &in.Code, &out.Code
		*out = new(string)
		**out = **in
	}
	if in.Coupon != nil {
		in, out := &in.Coupon, &out.Coupon
		*out = new(string)
		**out = **in
	}
	if in.Customer != nil {
		in, out := &in.Customer, &out.Customer
		*out = new(string)
		**out = **in
	}
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = new(string)
		**out = **in
	}
	if in.MaxRedemptions != nil {
		in, out := &in.MaxRedemptions, &out.MaxRedemptions
		*out = new(float64)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Restrictions != nil {
		in, out := &in.Restrictions, &out.Restrictions
		*out = make([]RestrictionsParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeParameters.
func (in *CodeParameters) DeepCopy() *CodeParameters {
	if in == nil {
		return nil
	}
	out := new(CodeParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeSpec) DeepCopyInto(out *CodeSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeSpec.
func (in *CodeSpec) DeepCopy() *CodeSpec {
	if in == nil {
		return nil
	}
	out := new(CodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CodeStatus) DeepCopyInto(out *CodeStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CodeStatus.
func (in *CodeStatus) DeepCopy() *CodeStatus {
	if in == nil {
		return nil
	}
	out := new(CodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestrictionsInitParameters) DeepCopyInto(out *RestrictionsInitParameters) {
	*out = *in
	if in.FirstTimeTransaction != nil {
		in, out := &in.FirstTimeTransaction, &out.FirstTimeTransaction
		*out = new(bool)
		**out = **in
	}
	if in.MinimumAmount != nil {
		in, out := &in.MinimumAmount, &out.MinimumAmount
		*out = new(float64)
		**out = **in
	}
	if in.MinimumAmountCurrency != nil {
		in, out := &in.MinimumAmountCurrency, &out.MinimumAmountCurrency
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestrictionsInitParameters.
func (in *RestrictionsInitParameters) DeepCopy() *RestrictionsInitParameters {
	if in == nil {
		return nil
	}
	out := new(RestrictionsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestrictionsObservation) DeepCopyInto(out *RestrictionsObservation) {
	*out = *in
	if in.FirstTimeTransaction != nil {
		in, out := &in.FirstTimeTransaction, &out.FirstTimeTransaction
		*out = new(bool)
		**out = **in
	}
	if in.MinimumAmount != nil {
		in, out := &in.MinimumAmount, &out.MinimumAmount
		*out = new(float64)
		**out = **in
	}
	if in.MinimumAmountCurrency != nil {
		in, out := &in.MinimumAmountCurrency, &out.MinimumAmountCurrency
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestrictionsObservation.
func (in *RestrictionsObservation) DeepCopy() *RestrictionsObservation {
	if in == nil {
		return nil
	}
	out := new(RestrictionsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestrictionsParameters) DeepCopyInto(out *RestrictionsParameters) {
	*out = *in
	if in.FirstTimeTransaction != nil {
		in, out := &in.FirstTimeTransaction, &out.FirstTimeTransaction
		*out = new(bool)
		**out = **in
	}
	if in.MinimumAmount != nil {
		in, out := &in.MinimumAmount, &out.MinimumAmount
		*out = new(float64)
		**out = **in
	}
	if in.MinimumAmountCurrency != nil {
		in, out := &in.MinimumAmountCurrency, &out.MinimumAmountCurrency
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestrictionsParameters.
func (in *RestrictionsParameters) DeepCopy() *RestrictionsParameters {
	if in == nil {
		return nil
	}
	out := new(RestrictionsParameters)
	in.DeepCopyInto(out)
	return out
}
