// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type RateInitParameters struct {

	// Bool. Flag determining whether the tax rate is active or inactive (archived). Inactive tax rates cannot be used with new applications or Checkout Sessions, but will still work for subscriptions and invoices that already have it set.
	// Flag determining whether the tax rate is active or inactive (archived). Inactive tax rates cannot be used with new applications or Checkout Sessions, but will still work for subscriptions and invoices that already have it set.
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// String. Two-letter country code (ISO 3166-1 alpha-2).
	// Two-letter country code (ISO 3166-1 alpha-2).
	Country *string `json:"country,omitempty" tf:"country,omitempty"`

	// String. An arbitrary string attached to the tax rate for your internal use only. It will not be visible to your customers.
	// An arbitrary string attached to the tax rate for your internal use only. It will not be visible to your customers.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// String. The display name of the tax rate, which will be shown to users.
	// The display name of the tax rate, which will be shown to users.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// Bool. This specifies if the tax rate is inclusive or exclusive.
	// This specifies if the tax rate is inclusive or exclusive.
	Inclusive *bool `json:"inclusive,omitempty" tf:"inclusive,omitempty"`

	// String. The jurisdiction for the tax rate. You can use this label field for tax reporting purposes. It also appears on your customer’s invoice.
	// The jurisdiction for the tax rate. You can use this label field for tax reporting purposes.It also appears on your customer’s invoice.
	Jurisdiction *string `json:"jurisdiction,omitempty" tf:"jurisdiction,omitempty"`

	// Map(String). Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to metadata.
	// Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to metadata.
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// This represents the tax rate percent out of 100.
	Percentage *float64 `json:"percentage,omitempty" tf:"percentage,omitempty"`

	// String. ISO 3166-2 subdivision code, without country prefix. For example, “NY” for New York, United States.
	// ISO 3166-2 subdivision code, without country prefix. For example, “NY” for New York, United States.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// String. The high-level tax type, such as vat or sales_tax.
	// The high-level tax type, such as vat or sales_tax.
	TaxType *string `json:"taxType,omitempty" tf:"tax_type,omitempty"`
}

type RateObservation struct {

	// Bool. Flag determining whether the tax rate is active or inactive (archived). Inactive tax rates cannot be used with new applications or Checkout Sessions, but will still work for subscriptions and invoices that already have it set.
	// Flag determining whether the tax rate is active or inactive (archived). Inactive tax rates cannot be used with new applications or Checkout Sessions, but will still work for subscriptions and invoices that already have it set.
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// String. Two-letter country code (ISO 3166-1 alpha-2).
	// Two-letter country code (ISO 3166-1 alpha-2).
	Country *string `json:"country,omitempty" tf:"country,omitempty"`

	// Int. Time at which the object was created. Measured in seconds since the Unix epoch.
	// Time at which the object was created. Measured in seconds since the Unix epoch.
	Created *float64 `json:"created,omitempty" tf:"created,omitempty"`

	// String. An arbitrary string attached to the tax rate for your internal use only. It will not be visible to your customers.
	// An arbitrary string attached to the tax rate for your internal use only. It will not be visible to your customers.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// String. The display name of the tax rate, which will be shown to users.
	// The display name of the tax rate, which will be shown to users.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// String. The unique identifier for the object.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Bool. This specifies if the tax rate is inclusive or exclusive.
	// This specifies if the tax rate is inclusive or exclusive.
	Inclusive *bool `json:"inclusive,omitempty" tf:"inclusive,omitempty"`

	// String. The jurisdiction for the tax rate. You can use this label field for tax reporting purposes. It also appears on your customer’s invoice.
	// The jurisdiction for the tax rate. You can use this label field for tax reporting purposes.It also appears on your customer’s invoice.
	Jurisdiction *string `json:"jurisdiction,omitempty" tf:"jurisdiction,omitempty"`

	// Bool. Has the value true if the object exists in live mode or the value false if the object exists in test mode.
	// Has the value true if the object exists in live mode or the value false if the object exists in test mode.
	Livemode *bool `json:"livemode,omitempty" tf:"livemode,omitempty"`

	// Map(String). Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to metadata.
	// Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to metadata.
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// String. String representing the object’s type. Objects of the same type share the same value.
	// String representing the object’s type. Objects of the same type share the same value.
	Object *string `json:"object,omitempty" tf:"object,omitempty"`

	// This represents the tax rate percent out of 100.
	Percentage *float64 `json:"percentage,omitempty" tf:"percentage,omitempty"`

	// String. ISO 3166-2 subdivision code, without country prefix. For example, “NY” for New York, United States.
	// ISO 3166-2 subdivision code, without country prefix. For example, “NY” for New York, United States.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// String. The high-level tax type, such as vat or sales_tax.
	// The high-level tax type, such as vat or sales_tax.
	TaxType *string `json:"taxType,omitempty" tf:"tax_type,omitempty"`
}

type RateParameters struct {

	// Bool. Flag determining whether the tax rate is active or inactive (archived). Inactive tax rates cannot be used with new applications or Checkout Sessions, but will still work for subscriptions and invoices that already have it set.
	// Flag determining whether the tax rate is active or inactive (archived). Inactive tax rates cannot be used with new applications or Checkout Sessions, but will still work for subscriptions and invoices that already have it set.
	// +kubebuilder:validation:Optional
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// String. Two-letter country code (ISO 3166-1 alpha-2).
	// Two-letter country code (ISO 3166-1 alpha-2).
	// +kubebuilder:validation:Optional
	Country *string `json:"country,omitempty" tf:"country,omitempty"`

	// String. An arbitrary string attached to the tax rate for your internal use only. It will not be visible to your customers.
	// An arbitrary string attached to the tax rate for your internal use only. It will not be visible to your customers.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// String. The display name of the tax rate, which will be shown to users.
	// The display name of the tax rate, which will be shown to users.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// Bool. This specifies if the tax rate is inclusive or exclusive.
	// This specifies if the tax rate is inclusive or exclusive.
	// +kubebuilder:validation:Optional
	Inclusive *bool `json:"inclusive,omitempty" tf:"inclusive,omitempty"`

	// String. The jurisdiction for the tax rate. You can use this label field for tax reporting purposes. It also appears on your customer’s invoice.
	// The jurisdiction for the tax rate. You can use this label field for tax reporting purposes.It also appears on your customer’s invoice.
	// +kubebuilder:validation:Optional
	Jurisdiction *string `json:"jurisdiction,omitempty" tf:"jurisdiction,omitempty"`

	// Map(String). Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to metadata.
	// Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to metadata.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// This represents the tax rate percent out of 100.
	// +kubebuilder:validation:Optional
	Percentage *float64 `json:"percentage,omitempty" tf:"percentage,omitempty"`

	// String. ISO 3166-2 subdivision code, without country prefix. For example, “NY” for New York, United States.
	// ISO 3166-2 subdivision code, without country prefix. For example, “NY” for New York, United States.
	// +kubebuilder:validation:Optional
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// String. The high-level tax type, such as vat or sales_tax.
	// The high-level tax type, such as vat or sales_tax.
	// +kubebuilder:validation:Optional
	TaxType *string `json:"taxType,omitempty" tf:"tax_type,omitempty"`
}

// RateSpec defines the desired state of Rate
type RateSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            RateParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RateInitParameters `json:"initProvider,omitempty"`
}

// RateStatus defines the observed state of Rate.
type RateStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RateObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Rate is the Schema for the Rates API. The Stripe Tax Rate can be created, modified and configured by this resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,stripe}
type Rate struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.displayName) || (has(self.initProvider) && has(self.initProvider.displayName))",message="spec.forProvider.displayName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.inclusive) || (has(self.initProvider) && has(self.initProvider.inclusive))",message="spec.forProvider.inclusive is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.percentage) || (has(self.initProvider) && has(self.initProvider.percentage))",message="spec.forProvider.percentage is a required parameter"
	Spec   RateSpec   `json:"spec"`
	Status RateStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RateList contains a list of Rates
type RateList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Rate `json:"items"`
}

// Repository type metadata.
var (
	Rate_Kind             = "Rate"
	Rate_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Rate_Kind}.String()
	Rate_KindAPIVersion   = Rate_Kind + "." + CRDGroupVersion.String()
	Rate_GroupVersionKind = CRDGroupVersion.WithKind(Rate_Kind)
)

func init() {
	SchemeBuilder.Register(&Rate{}, &RateList{})
}
