// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type CodeInitParameters struct {

	// Bool. Whether the promotion code is currently active. Defaults to true.
	// Whether the promotion code is currently active.
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// String. The customer-facing code. Regardless of case, this code must be unique across all active promotion codes for a specific customer. If left blank, we will generate one automatically.
	// The customer-facing code. Regardless of case, this code must be unique across all active promotion codes for a specific customer. If left blank, we will generate one automatically.
	Code *string `json:"code,omitempty" tf:"code,omitempty"`

	// String. The coupon for this promotion code.
	// The coupon for this promotion code.
	Coupon *string `json:"coupon,omitempty" tf:"coupon,omitempty"`

	// String. The customer that this promotion code can be used by. If not set, the promotion code can be used by all customers.
	// The customer that this promotion code can be used by. If not set, the promotion code can be used by all customers.
	Customer *string `json:"customer,omitempty" tf:"customer,omitempty"`

	// String. The timestamp at which this promotion code will expire. If the coupon has specified a redeems_by, then this value cannot be after the coupon’s redeems_by. Expected format is RFC3339.
	// The timestamp at which this promotion code will expire. If the coupon has specified a redeems_by, then this value cannot be after the coupon’s redeems_by. Expected format is RFC3339
	ExpiresAt *string `json:"expiresAt,omitempty" tf:"expires_at,omitempty"`

	// Int. A positive integer specifying the number of times the promotion code can be redeemed. If the coupon has specified a max_redemptions, then this value cannot be greater than the coupon’s max_redemptions.
	// A positive integer specifying the number of times the promotion code can be redeemed. If the coupon has specified a max_redemptions, then this value cannot be greater than the coupon’s max_redemptions.
	MaxRedemptions *float64 `json:"maxRedemptions,omitempty" tf:"max_redemptions,omitempty"`

	// Map(String). Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
	// Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// List(Resource). Settings that restrict the redemption of the promotion code. For details of individual arguments see Restrictions.
	// Settings that restrict the redemption of the promotion code.
	Restrictions []RestrictionsInitParameters `json:"restrictions,omitempty" tf:"restrictions,omitempty"`
}

type CodeObservation struct {

	// Bool. Whether the promotion code is currently active. Defaults to true.
	// Whether the promotion code is currently active.
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// String. The customer-facing code. Regardless of case, this code must be unique across all active promotion codes for a specific customer. If left blank, we will generate one automatically.
	// The customer-facing code. Regardless of case, this code must be unique across all active promotion codes for a specific customer. If left blank, we will generate one automatically.
	Code *string `json:"code,omitempty" tf:"code,omitempty"`

	// String. The coupon for this promotion code.
	// The coupon for this promotion code.
	Coupon *string `json:"coupon,omitempty" tf:"coupon,omitempty"`

	// String. The customer that this promotion code can be used by. If not set, the promotion code can be used by all customers.
	// The customer that this promotion code can be used by. If not set, the promotion code can be used by all customers.
	Customer *string `json:"customer,omitempty" tf:"customer,omitempty"`

	// String. The timestamp at which this promotion code will expire. If the coupon has specified a redeems_by, then this value cannot be after the coupon’s redeems_by. Expected format is RFC3339.
	// The timestamp at which this promotion code will expire. If the coupon has specified a redeems_by, then this value cannot be after the coupon’s redeems_by. Expected format is RFC3339
	ExpiresAt *string `json:"expiresAt,omitempty" tf:"expires_at,omitempty"`

	// String. The unique identifier for the object.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Int. A positive integer specifying the number of times the promotion code can be redeemed. If the coupon has specified a max_redemptions, then this value cannot be greater than the coupon’s max_redemptions.
	// A positive integer specifying the number of times the promotion code can be redeemed. If the coupon has specified a max_redemptions, then this value cannot be greater than the coupon’s max_redemptions.
	MaxRedemptions *float64 `json:"maxRedemptions,omitempty" tf:"max_redemptions,omitempty"`

	// Map(String). Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
	// Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// List(Resource). Settings that restrict the redemption of the promotion code. For details of individual arguments see Restrictions.
	// Settings that restrict the redemption of the promotion code.
	Restrictions []RestrictionsObservation `json:"restrictions,omitempty" tf:"restrictions,omitempty"`
}

type CodeParameters struct {

	// Bool. Whether the promotion code is currently active. Defaults to true.
	// Whether the promotion code is currently active.
	// +kubebuilder:validation:Optional
	Active *bool `json:"active,omitempty" tf:"active,omitempty"`

	// String. The customer-facing code. Regardless of case, this code must be unique across all active promotion codes for a specific customer. If left blank, we will generate one automatically.
	// The customer-facing code. Regardless of case, this code must be unique across all active promotion codes for a specific customer. If left blank, we will generate one automatically.
	// +kubebuilder:validation:Optional
	Code *string `json:"code,omitempty" tf:"code,omitempty"`

	// String. The coupon for this promotion code.
	// The coupon for this promotion code.
	// +kubebuilder:validation:Optional
	Coupon *string `json:"coupon,omitempty" tf:"coupon,omitempty"`

	// String. The customer that this promotion code can be used by. If not set, the promotion code can be used by all customers.
	// The customer that this promotion code can be used by. If not set, the promotion code can be used by all customers.
	// +kubebuilder:validation:Optional
	Customer *string `json:"customer,omitempty" tf:"customer,omitempty"`

	// String. The timestamp at which this promotion code will expire. If the coupon has specified a redeems_by, then this value cannot be after the coupon’s redeems_by. Expected format is RFC3339.
	// The timestamp at which this promotion code will expire. If the coupon has specified a redeems_by, then this value cannot be after the coupon’s redeems_by. Expected format is RFC3339
	// +kubebuilder:validation:Optional
	ExpiresAt *string `json:"expiresAt,omitempty" tf:"expires_at,omitempty"`

	// Int. A positive integer specifying the number of times the promotion code can be redeemed. If the coupon has specified a max_redemptions, then this value cannot be greater than the coupon’s max_redemptions.
	// A positive integer specifying the number of times the promotion code can be redeemed. If the coupon has specified a max_redemptions, then this value cannot be greater than the coupon’s max_redemptions.
	// +kubebuilder:validation:Optional
	MaxRedemptions *float64 `json:"maxRedemptions,omitempty" tf:"max_redemptions,omitempty"`

	// Map(String). Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
	// Set of key-value pairs that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Metadata map[string]*string `json:"metadata,omitempty" tf:"metadata,omitempty"`

	// List(Resource). Settings that restrict the redemption of the promotion code. For details of individual arguments see Restrictions.
	// Settings that restrict the redemption of the promotion code.
	// +kubebuilder:validation:Optional
	Restrictions []RestrictionsParameters `json:"restrictions,omitempty" tf:"restrictions,omitempty"`
}

type RestrictionsInitParameters struct {

	// Bool. A Boolean indicating if the Promotion Code should only be redeemed for Customers without any successful payments or invoices.
	// A Boolean indicating if the Promotion Code should only be redeemed for Customers without any successful payments or invoices
	FirstTimeTransaction *bool `json:"firstTimeTransaction,omitempty" tf:"first_time_transaction,omitempty"`

	// Int. Minimum amount required to redeem this Promotion Code into a Coupon (e.g., a purchase must be $100 or more to work).
	// Minimum amount required to redeem this Promotion Code into a Coupon (e.g., a purchase must be $100 or more to work).
	MinimumAmount *float64 `json:"minimumAmount,omitempty" tf:"minimum_amount,omitempty"`

	// String. Three-letter ISO code for minimum_amount.
	// Three-letter ISO code for minimum_amount
	MinimumAmountCurrency *string `json:"minimumAmountCurrency,omitempty" tf:"minimum_amount_currency,omitempty"`
}

type RestrictionsObservation struct {

	// Bool. A Boolean indicating if the Promotion Code should only be redeemed for Customers without any successful payments or invoices.
	// A Boolean indicating if the Promotion Code should only be redeemed for Customers without any successful payments or invoices
	FirstTimeTransaction *bool `json:"firstTimeTransaction,omitempty" tf:"first_time_transaction,omitempty"`

	// Int. Minimum amount required to redeem this Promotion Code into a Coupon (e.g., a purchase must be $100 or more to work).
	// Minimum amount required to redeem this Promotion Code into a Coupon (e.g., a purchase must be $100 or more to work).
	MinimumAmount *float64 `json:"minimumAmount,omitempty" tf:"minimum_amount,omitempty"`

	// String. Three-letter ISO code for minimum_amount.
	// Three-letter ISO code for minimum_amount
	MinimumAmountCurrency *string `json:"minimumAmountCurrency,omitempty" tf:"minimum_amount_currency,omitempty"`
}

type RestrictionsParameters struct {

	// Bool. A Boolean indicating if the Promotion Code should only be redeemed for Customers without any successful payments or invoices.
	// A Boolean indicating if the Promotion Code should only be redeemed for Customers without any successful payments or invoices
	// +kubebuilder:validation:Optional
	FirstTimeTransaction *bool `json:"firstTimeTransaction" tf:"first_time_transaction,omitempty"`

	// Int. Minimum amount required to redeem this Promotion Code into a Coupon (e.g., a purchase must be $100 or more to work).
	// Minimum amount required to redeem this Promotion Code into a Coupon (e.g., a purchase must be $100 or more to work).
	// +kubebuilder:validation:Optional
	MinimumAmount *float64 `json:"minimumAmount,omitempty" tf:"minimum_amount,omitempty"`

	// String. Three-letter ISO code for minimum_amount.
	// Three-letter ISO code for minimum_amount
	// +kubebuilder:validation:Optional
	MinimumAmountCurrency *string `json:"minimumAmountCurrency,omitempty" tf:"minimum_amount_currency,omitempty"`
}

// CodeSpec defines the desired state of Code
type CodeSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     CodeParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CodeInitParameters `json:"initProvider,omitempty"`
}

// CodeStatus defines the observed state of Code.
type CodeStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CodeObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Code is the Schema for the Codes API. The Stripe Promotion Code can be created, modified and configured by this resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,stripe}
type Code struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.coupon) || (has(self.initProvider) && has(self.initProvider.coupon))",message="spec.forProvider.coupon is a required parameter"
	Spec   CodeSpec   `json:"spec"`
	Status CodeStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CodeList contains a list of Codes
type CodeList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Code `json:"items"`
}

// Repository type metadata.
var (
	Code_Kind             = "Code"
	Code_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Code_Kind}.String()
	Code_KindAPIVersion   = Code_Kind + "." + CRDGroupVersion.String()
	Code_GroupVersionKind = CRDGroupVersion.WithKind(Code_Kind)
)

func init() {
	SchemeBuilder.Register(&Code{}, &CodeList{})
}
