apiVersion: stripepromotioncode.stripe.crossplane.io/v1alpha1
kind: PromotionCode
metadata:
  annotations:
    meta.upbound.io/example-id: stripepromotioncode/v1alpha1/promotioncode
  labels:
    testing.upbound.io/example-name: code
  name: code
spec:
  forProvider:
    code: FREE
    coupon: ${stripe_coupon.coupon.id}
